apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: mi-carpeta-medica-api
  namespace: mi-carpeta-medica-dev
spec:
  imageRepositoryRef:
    name: mi-carpeta-medica-api
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^dev-(?P<num>[0-9]+)$'
    extract: '$num'
