apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: nayeong-song
  namespace: lulo-demo-landings
spec:
  image: registry.yesidlopez.de/nayeong-song
  interval: 1m
  secretRef:
    name: registry-secret
