---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: on-call
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: error
  exclusionList:
    - "kustomization/flux-system"
  eventSources:
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: GitRepository
      name: '*'
    - kind: ImageUpdateAutomation
      name: '*'
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: on-call-info
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: docker-registry
      namespace: registry
    - kind: HelmRelease
      name: docker-registry-ui
      namespace: registry
    - kind: HelmRelease
      name: gotenberg
      namespace: resumelo
    - kind: HelmRelease
      name: umami
      namespace: umami
    - kind: ImageUpdateAutomation
      name: resumelo-dev
      namespace: resumelo-dev
    - kind: ImageUpdateAutomation
      name: resumelo-prod
      namespace: resumelo
    - kind: ImageUpdateAutomation
      name: macondo-prod
      namespace: macondo
    - kind: ImageUpdateAutomation
      name: ebay-kleinanzeigen-api
      namespace: ebay-kleinanzeigen-api
    - kind: GitRepository
      name: docker-registry
      namespace: flux-system
