apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBwKxiIQvIimrEhs8s+Qjv79TJjcMJJ7K2me3yrQmCRCPFRaMUE5td5cn9aNurIzzMwneV4bpLh32knak26bhigX5M+hKVci2FGhGjjZwqWjBLzvKSngNbsB5m5aUpI71QxtKST504/aK+DC7Jo4qMBlWsvQExenDBeFBTZTkggO8MM0XP5qGbM6J33H2CxEqPlXBIzbSrStHXTjk/h5S57auyFve/prtjmwjW8mVPhAaO4Ca4egy8NY01KDowsoycaS9sRmbytSjKYwPMb/98Ctk3je4wHLutTzpukOjK0wdR0RU0IaaS40NV00X3wOlyx126M03NmQqIc/BuLBeJRk7OH6j68/C0AMao+EYXDLnxOF/+pL8bVMK6j1penffjEY2zg6AkjbfgrrA57V1EI4uPx3G676FgwrdpccM5YIRHW9lZ/EIIiutGlOFM6oAjO8MXYcMlzO0AF8uQzRCNrCnV/W6uEhzVIEIY2MW2Z6CTY+tVsJX69G/651DHE7zi/dT4hpAkRl8zu9dIp/xFmC92lE+eAzZuwmXLRviFT5/OPVA/RjktJYVls5KWa20y0lGmHeRbKkTRrOVVlmN94Y65t6j/eBF04rbp8MRHugfHW/QhCUa4StHvBRaQeKmm/E6OCcNIxYzjaB+9/HPJWi3B/gVao7CHtx0ebaLFTXZG+BJjZz2LfGG6kApehUWCkmIndWTXlq3seyfxAvpM5IYHugXy2TS6jWX0jXWUfAMucvO/uXJM1OTqITZhxWCWZwNApMPOy6mrqCdP8cGu7iJOMiKAlfihvgSeT79xcHjjVOOtfwsFCfyIgNM8XSbZ3KfwcAOUKsHtVOTDRSEMwt9wtVU0Iqn0/
  template:
    metadata:
      name: discord-webhook-url
      namespace: flux-system
