apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resumelo-ingress
  namespace: resumelo-dev
spec:
  tls:
    - hosts:
        - api-dev.resumelo.me
  rules:
    - host: api-dev.resumelo.me
