apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - image-automation
  - sealed-secrets
  - mongodb.yaml

namespace: resumelo-dev

patches:
- path: namespace-patch.yaml
  target:
    kind: Namespace
    name: resumelo
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: resumelo
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: configmap 
