---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-values
  namespace: longhorn-system
data:
  values.yaml: |
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      # Disable automatic system snapshot creation
      autoCleanupSystemGeneratedSnapshot: false
      # Set minimum snapshot count
      snapshotMaxCount: 2
      # Enable snapshot purging
      disableSnapshotPurge: false
