---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: ebay-kleinanzeigen-api
spec:
  encryptedData:
    .dockerconfigjson: AgAq6/48y9H7rvMDjFLvuepJZi+6u3HItBqbm46fhyL0CP0sLqtPM8MvDrdCWHLdx0/rsxDfB3dzHWk/b38lR2rUEwvO2VMiKcEwaMFcQdRYScJJ8iIXsJdLzOrH7YIkgcSLrGrKL9SDmGEvvcpeX74vQ7HVbT40qUBbl2zWHSbJug0zPhnlDTDVt2yIKRAyHC2AeuP4PPmBh+538UVAAHRbI7wBCaB5YUet9k5julZlLAVGqFY9LjQLd7P/NZDHkw67S9EWqKkvzb12g38eCs4IEjAgw8PvEzImEI8ON9ybw80E8jFnCuFt4aWZyP1Qx/7OrqhXxN7R5yBade+zdCK+VHiG4iZs4WyaO2724WuuakiPzPdYMQXmZC8br15D1n7blgibeLTS+FNzEBF+PSEHNX/1zqeqks9PxBE8FVbFeINnY77B8zI2YlWNfDfp7DDE8tiFSrCLOo8o4y7cfXboM6tXOxYz3qxrrkYrNNFB/jIEFo308/Fvj4vFCoLxFLFtRMPr41I/CW7O7SXuqjW0fIQ1BwUXsHZ2f4rakI5U18r/tzTZmuDThBClwGf6lp0OmCCN3g9sMVi+9KAgRgebFRnieGUoH88xJk+UOGsny3Y9a/kdTS1yl+er/wZXDA0ZBgs9pjvasm2UegFIyDkEdObBW/WHEoH0chiqZY1rcHpUVq4zijWGUaeViW5PFn0gQKyZIIasjT9jcLCpqDR4ZoxyAXYXyxz43wxYwkLiUq0zMbSwiaNBwT13MLdKuH1ob4V4+0TCjI1hZkrSiorbe/cKqykF7kjd+dFkRFjBfg4JYAH219KoQAEWT8Msa27RJzD9sYbsPZcQbY6Un+3h+G+AdtZgOD7H1X1CB4whwoQQrIMBsP/zHvYMr1V2XdhH5GPS0S5ZMV4NLY7Rl8oR7Bn214xFQwFlQPfkAWM=
  template:
    metadata:
      name: registry-secret
      namespace: ebay-kleinanzeigen-api
    type: kubernetes.io/dockerconfigjson
