apiVersion: v1
kind: Service
metadata:
  name: ebay-kleinanzeigen-api
  namespace: ebay-kleinanzeigen-api
spec:
  selector:
    app: ebay-kleinanzeigen-api
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
