apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: maria-elvira
  namespace: lulo-demo-landings
spec:
  image: registry.yesidlopez.de/maria-elvira
  interval: 1m
  secretRef:
    name: registry-secret
