apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: maria-elvira
  namespace: lulo-demo-landings
spec:
  imageRepositoryRef:
    name: maria-elvira
  policy:
    semver:
      range: ">=0.0.0"
  filterTags:
    pattern: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
    extract: '$0'
