apiVersion: v1
kind: ConfigMap
metadata:
  name: gotenberg-helm-chart-value-overrides
  namespace: resumelo
data:
  values.yaml: |-
    securityContext:
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      privileged: false
      runAsUser: 1001
      runAsGroup: 1001
      runAsNonRoot: true
    
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    
    service:
      type: ClusterIP
      port: 3000
    
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "resumelo-issuer"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        external-dns.alpha.kubernetes.io/target: homelab.resumelo.me
      hosts:
        - host: gotenberg.resumelo.me
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gotenberg-tls
          hosts:
            - gotenberg.resumelo.me
    
    replicaCount: 1
    
    # Health checks
    livenessProbe:
      httpGet:
        path: /health
        port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
    
    readinessProbe:
      httpGet:
        path: /health
        port: 3000
      initialDelaySeconds: 5
      periodSeconds: 5 
