apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gotenberg
  namespace: resumelo
spec:
  interval: 30m
  chart:
    spec:
      chart: gotenberg
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: maikumori
        namespace: resumelo
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: gotenberg-helm-chart-value-overrides
      valuesKey: values.yaml
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3 
