---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: thingiverse-mcp
spec:
  encryptedData:
    .dockerconfigjson: AgCLCv2liE9oFv0AptSbrjvF26XvkfpTESXWfK6rjjM0Z+EKxPUh1XTSN9iJw0KltPuHD3+u2zhiaKr//QYfNi0q/tzwysEwBSPd4atN7WYqPPEwz5stoL4wBbmTtEkeacplANPADUy3HbtOZehtoWwlVHF1sjFxPPQTNftbTP9R20MXhWe0VgPlD9w29Deqogbk5eib4bz5cdj9+biKv+IUmzZNTPRNQt+jxHP4lJtmBWwkZNGdTkip8TOlZSL/Y2vrdwVDHCpbOc3kLwE9qx7ZxZTfWFD6Uhlqjto1Ow0xDQVzYK9/wK5ffLr98r7/FCl1RiotXk7nFyQpOqsinIBWODdQPJm+p2UueQcSSLF5oGOV/SQmK4gPq8j3Eb1QoEuArdYbUw7A17SuJX3CzxDPiC4AILGE8xJowMMkmMBJZoCq9g42tsMWqb7RAoMi5QKepDuWS1zUJyWVdImrC5MdTkt2gW/lGFrfODsdfnPiy/YFND80BUhDzfeBF51QIsatiP4WVD/Nn7pR+AWKqKbizfGvhTyqvnPcQW0K2dCNFPSFE5hADuYqR3xjbvGbBSLUgvoQeIscwHDqLq50SkjecFt7n0m88zKwWupt46CqXMnR0MoqWO0OKFIjMPOTzzu1jGCloibbxzeL4AAy33RyfMQ0wYyVSliQEfHC8MqaeTgmAH+RQ4CLX4V7tGMTDaETSLbi0v6Udpzn2dc42yYKB/Aux1+++5VXdC6DKswKVcl/rsm/y0XrLB2w3lAQnqGHWT1PSki2edCYI/15kG2prQAR/duAzRhlaKgy1thdUW9wb6h90xuoiSqgQtwObI0vhO6nCA0ajq+s4s8FOH+jLhpNsqhlF4pzoKHziPdofDyX1QSqAq0BIP364hU3RSnn2tlHD9yWzSZWLD6ntvJitVlOnM1to46QQH52IQvyqqFC/alQwXkfiJsgxW2ON8YCwScQ5yFkiWlKFeWLrICd2/HCHAZMUpOce3A/j3HtfU9y
  template:
    metadata:
      name: registry-secret
      namespace: thingiverse-mcp
    type: kubernetes.io/dockerconfigjson
