---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thingiverse-mcp-secrets
  namespace: thingiverse-mcp
spec:
  encryptedData:
    THINGIVERSE_APP_TOKEN: AgBPUkr+xnMosRDkWOTK/lZe/t+TUdFPPpAjpUtvVLMVbAEl6U2qytj50yScutyILGnSndEPWF2pCYAh3xDllJwYOvtbR3ai5IKIljfn7GJ/l0SE9hOSoTrw/Z/DbIITDx80k4c7klmsrl0BMwan7N89e4wTKGeDdKzIrWovmmsjW8SWwTYRIPG5vVHlTrZFJPBUq6TVTeGcgJ3QC9JrV4F8AP9ozVDOrxK7qBSwzG85VjcJA/DuqQlAoecm9A9lmsFS2Tl3coi0MqbhpMRufj0VcQKjhNdkrAhwH5BOHjzvypVzoDpioWOqiyG6cVAgQNYsbT35/9mxJ0EPwtvvVYnzE9C4ylruz2ZGmmd7gNPwqtLDGxccIFXgBMKyw/Qtm2dpfYMBz8HK2yP29FiQJGS/2kATW4SOnDRPbBnlY3qXN0g9DbkwkX8luhnOmpCzJzJIgXOpsbiwe+yFBB/aiHbN+f7l/QCIhB7ehT7RoOp9RBuIs9VmLDSG0fiSfIOv4fvNpzyhCENc8ETMOlpR+sCc6YRVKpXoO6pD0l9+plVijkURSXAYqpigQ8wcNlf/qDCBFnomh1Dv9L4pNYrhTN+DTHgRwpq8Eg+iNfZM5zJTZseBw64CShbG1VbUHalPShw8IHxd8ZTnXcYbGjCy7ObSJHDZsEzjzmefAB5hy06JFj6F0WI5EyWhuiy+0b/o8dR4BNvA9itJg57zzS13Jv+2uCNUiFZgNOLRBffUSHLBHg==
  template:
    metadata:
      name: thingiverse-mcp-secrets
      namespace: thingiverse-mcp
