apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-carpeta-medica-api-redis
  namespace: mi-carpeta-medica-api
  labels:
    app: mi-carpeta-medica-api-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mi-carpeta-medica-api-redis
  template:
    metadata:
      labels:
        app: mi-carpeta-medica-api-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests: {memory: "64Mi", cpu: "50m"}
            limits: {memory: "256Mi", cpu: "250m"}
          readinessProbe:
            exec: {command: ["redis-cli", "ping"]}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec: {command: ["redis-cli", "ping"]}
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: mi-carpeta-medica-api-redis
  namespace: mi-carpeta-medica-api
spec:
  selector:
    app: mi-carpeta-medica-api-redis
  ports:
    - port: 6379
      targetPort: 6379
