---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: porkbun-credentials:reader
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["porkbun-credentials"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porkbun-webhook:key-reader
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: porkbun-credentials:reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: porkbun-webhook
    namespace: cert-manager

