---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cert-manager
  name: porkbun-webhook:secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porkbun-webhook:secret-reader
  namespace: cert-manager
subjects:
- kind: ServiceAccount
  name: porkbun-webhook
  namespace: cert-manager
roleRef:
  kind: Role
  name: porkbun-webhook:secret-reader
  apiGroup: rbac.authorization.k8s.io 
