apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-ui-helm-chart-value-overrides
  namespace: registry
data:
  values.yaml: |-
    ui:
      replicas: 1
      dockerRegistryUrl: "https://registry.yesidlopez.de"
      deleteImages: true
      singleRegistry: true
      image: "joxit/docker-registry-ui:latest"
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
      service:
        type: ClusterIP
        port: 80
        targetPort: 80
      
      ingress:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "registry-ui.yesidlopez.de"
          external-dns.alpha.kubernetes.io/target: "homelab.yesidlopez.de"
          cert-manager.io/cluster-issuer: "acme-issuer"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
        hosts:
          - host: registry-ui.yesidlopez.de
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: registry-ui-tls
            hosts:
              - registry-ui.yesidlopez.de 
