apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry-ui
  namespace: registry
spec:
  interval: 30m
  chart:
    spec:
      chart: docker-registry-ui
      version: ">=2.5.0"
      sourceRef:
        kind: HelmRepository
        name: joxit
        namespace: registry
      interval: 12h
  values:
    ui:
      replicas: 1
      dockerRegistryUrl: "http://docker-registry:5000"
      deleteImages: true
      singleRegistry: true
      image: "joxit/docker-registry-ui:latest"
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
      service:
        type: LoadBalancer
        port: 80
        targetPort: 80
        annotations:
          metallb.universe.tf/loadBalancerIPs: "192.168.2.101" 
