apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry-ui
  namespace: registry
spec:
  interval: 30m
  chart:
    spec:
      chart: docker-registry-ui
      version: 1.5.2
      sourceRef:
        kind: HelmRepository
        name: joxit
        namespace: registry
      interval: 12h
  valuesFrom:
  - kind: ConfigMap
    name: docker-registry-ui-helm-chart-value-overrides
    valuesKey: values.yaml 
