---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mi-carpeta-medica-ui-secrets
  namespace: mi-carpeta-medica-dev
spec:
  encryptedData:
    API_KEY: AgCpSOcMz+m3ni2KBWnLmN3wUlzUylm+GVBmWwrL5pXRwV2AEp25FjUsgHNu6Oxo733swUyHHTXZ3jT6tVB7yL33+vT4fns095peMqtioKq5hNeTfAhb2bAzBLOi7yA4hzgJSsCl6bpAKGHYjXTAqKqlsDMXKxGJJ8kTKXKkmYI6pfonUis3Q9bT0oJ0R8uL+E8vCUZcB3B37YkuDQFuE9ui1FEdAPHTVb/nFuLbY0HiHd3bydzMIvoUnVVW7IZ64WRxUkWQYDoeO3zus3JtSTowpOL087IIQ7RPMeLOdk4ddtYEb9E+CFKzXHQWldTLlyqBKC54ZHiwX1aRGVO7EDYPps6D3YOyLbvr3E4ppjxifM45MzPBsr5r9oMtbToLXCdKIdIAB+oeigGfd16TD5S20IuEb2ApmI3rWTrbDBRr2R1Ry9XNQp8TSEG1RLuePLmFDtHy526K8YVnSriy6VXc3Zn1jffmHPxaxXKyMELjBx1cU4/ydnTa2rp2RGr0jad2wxorbzD8cK8KZPnnCvm9UxjiAaN6WKZCCmxNfluBZ4Qq2mB+uYluv8fiWBnn0qeZD7w7aWH9IZgohzgkH6XxfkIbd3FBBZL3STBgvJsvl9rLiyfdtyDzhc2PN4g8A+W1nIjRMk1v575ceJ3OqhxcpExPDDLKbAYqhZFUGB4H9fL6gFfEq+FG5JJOIWWIP3KcTOhS0rDdDGwbQxatTr6PJoh25z8nyo2wnE2Lk1/ya0UK3ZFjIOTsGXd2R5uOIz3kLt4NO4wO2NuidB7r3VPK
  template:
    metadata:
      name: mi-carpeta-medica-ui-secrets
      namespace: mi-carpeta-medica-dev
    type: Opaque
