---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: langfuse-secrets
  namespace: resumelo-dev
spec:
  encryptedData:
    LANGFUSE_PUBLIC_KEY: AgAD+62nAhsb1lxVEk5boUaMqmoPpuMpSp2XhCCJmAbMOJa4/APERTJH86nWkQO8p0v0ZzsvfkriNfpeXTf0zk7y9H1BonCUSrK9RH18M5zA7ymqa8ooii8AKhz1gZ1MTDt6w/RdRytBrk8ttO2xnN+bPuIPANwF3JoEKx7Gylw7qP6FuyypMsL8JtrUyt5c9jrzkY9Uz4gT6L3bsoMp9brig2mrmWwjb8XqGqY4vX7GQUgIJR6CWP1nkBU6LhJX+QaWqZhYT75qcvWSm/GSCDXN6to7KuodmNHjFp5SeQMH8TsrkUQk0R97cZA6/kxTKRXmWAomgWV98gSHw6vP5hEDjtiNY/Z8DPuyP8kSa+mwgNidxuJwQ23od/XomeAYW4oQM6hbvIDrqtVaWr6Fga62j2QvW9w+u+JpCJPvEIdN5tOHB8cciZzlwmlM3rXHiTyljKF+ttBSSSZBfhDc2nYhcTDxrD5B5q2v3nqoiE0YQRtFSj0fVoL4CPaB7GFWw7OrXuY4+ERkMNB14RX7npDFDj5HrdkKhn0o/+tlsRVKRyRpvY1EvFYlZ7HehVYByjnUUr592lgYOUO5RYcwKwSRtvy6ZYap+sHXKJf2Ux/BxTiHHqudZ5mWLAJSreLw1aYS+cUoCcVKW4D2eArUo7dSMnRVoRInaMCZOa3oS2C7raVfSMdqGu6r56kjTHxOECuLlCCvadyCy7OKfMbxP4abfW4eSQ+dphWxae66Lvlx0D+LMwylb2AFuN0=
    LANGFUSE_SECRET_KEY: AgCtu6NeOldTrGJ8t+6G/+Cph1XZsA0evg/AbmCQaNBGgDeWVFaVa6fOy8lB1S5mPsVlfHuxLu7kGgDjOEtlHthDApsSavM0zysHrQaesnQxBIUzNkVogx1KBACVVW8HqPyxOwIejuUX0MTCOhPwg/p3apULzmgGIbqmrykj15jHBTfADfxdg/+55cRrp8/fIDL9FmNdORISwi95h63/2sZZQgAJyocDhkRviXSW5VZ2832EgHf7MxKhYcIFhN0+nyD3NVyfYVUB9uXsFFdRAj72OhpLLkWo3+MaXi5ax+YgEF6HRVp/D6o1LOQkUTD1DF0Om9zR45iiuR2EjjOUdfvJyso53CauskgHMP9mvxqypVJiQaMDYBNmnJ36dWdG0z9sPPrwjYG0z44zgJWKSQEOuODSI+Ve3uNxRgiudVBK2T6kDCtbFGJjvB2uzxDZd6PeUapbFSSgcteo7MXRwNX1I/sHhzn+4V3sINe9njURXRdoOpGAMQUqArs5vbesYjCQlnsYu3eZRmri1sEcE2h58yZ9HSz8HTsyn3YQn/JWCDYTCvAhDHPtZPOCQOzYJ9+Kca9wzVD7Ycvro8sfk7cDYoffIGP8DmPABOVRVWWniahJBs3Owckb/fEXYh7HIsf+/H2Ezf0S88rsTsMPcFPZigItomKLuxtOCB1W85KcpGBTfL5tmJQx3P5sg7B4MtNH+mGvSSi5IITniRZczd83lXnGglkOh0EOq8Eux1+DBElmbO6Exc3wCco=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: resumelo
      name: langfuse-secrets
      namespace: resumelo-dev
    type: Opaque
