---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: maria-fernanda-espana-basic-auth
  namespace: lulo-demo-landings
spec:
  encryptedData:
    auth: AgCBwc7gYkMLYOxRZvYXIWexpUE8WMOkxreDGlHkE0ZMW9LPohbOSNiYZXa4Qpc8wadx76vNdWZ36gr3MeoK3egF22bjNCDVbtGy3X6MUbYwMnPAymnofbXgb/wVt+qHyc6bVtnTYwnykaJhgE85kyIUtJEyx3I7E0B763F45M9oVZAy0RSrm25iXt5gWFfAO4ubhJLX0/Gthnx6dCWxPv+o+Qc4fidsNLAMvsjYgRsPArHf8rQa/21UfpjLqUFiZyh+g7Lsuo06U30izAAxS1jUOhhFeQ6kPS5EWfntrmhxBSb9SxlqVbSBuL5WMnpg/WPNvRAFBb32iJW1PsN0W3QI7BJN5nFVcMK8oA1yRBi/sPJqLY1wpuYDFikOSb6mck9pS/xgDwQbHr0HWhz/X7piuxf0jBzcGoncaidXEiiGq2003bPPeNKMIyvSLuePaceeC8bQtbe0rJwz34S7RASCe+Vy6oE1Bm6hvxnyOa6XmHBUk4gW0MUPjNw64YkHQ9xYUHAvI14cOZMext6nl8J4uTnNemB+5ZQiyFPO+tuhzpXNdjWHUz91mq+dVSJOMUlGMsoFgRiFYxtWhQbHQUkJ0j/M+VdYeY8WB3V8dR8YRVhtzwlw1kAyV96GMwFbsFWMIBJ3Q9ABimlKPEY53noUbxz4th4SB1H7uRjdUae9WapmusFcNwnuZvdJ1jfzOGBTpY5ZLmll+CaPhFc5ndYCFWoUjgxgGs0iPeRXvM/4jQvOnCi9/Uox+0GsGph9
  template:
    metadata:
      name: maria-fernanda-espana-basic-auth
      namespace: lulo-demo-landings
    type: Opaque
