---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: mi-carpeta-medica-prod
spec:
  encryptedData:
    rootPassword: AgA/zq7cPr/Sd4WFwkNDs566jAxXTK5Ujvd/x/udtlO/Suiw8+cSkZS1W6pRp/wPtUmslUGL8Sst8p+VRSJYsZjAnLkO2rUJePKG32VQ+4+RZN9KgzdA3SEIjeMDh/izckKvDCkx4DSs9wiPJbAHizkGlMxdbJZGxAeukODR5pWO74vupxNW7wZ8pPnzdbMOTWnzWbO686sc9SGTNht9G7gbKbmUIBjps/KSOugBZofterOFMvoTAP5PTaZJFYXUyIHmGYXQuYkyXA7F/ngxH5PRNCv2I6sOnM60GRfxJ08CO2IeiLNNgvUoguBkdhqhAcXZam6DE1iCGWvAyzdf9hkr2SY451+LidFDPO57WtduHY/XAER3w3hDCTxoFuuj9SQZwDvKbJVPnzFS+fRih9bzRbnwmf8URmU1eV7l1RAuB5ThPFrPYtmbySF0JDEeK04HvM/RV8dFaZ9yAooO2jzbaFnBYSjoYH4X21T9jRujnzvvg1j1BjeqKyqizhRn4r0c6XrBkdmZwSlI63bS946GTwGkv2hIYyc2hZDw9VgLgB2OzEqCuF3wnMUy2duhiI2JmVTTqbMKGNEQiy0pLTOJzljlSzRCbzdpjqVwrHC66BoPWeMTvVRbCHhOJENsosnS/PyS4uYBeW+plJ3YLMu9tTuI3nthTzZQFrJ924KCpjd4xw5i7YFlfZjRHM80YtgNYBUI39XxK3oMG/Md3PDoPYlv4I1JKrQkrG4PayAq8s4jNEbfQRGL2jNpLIVrt78=
    rootUser: AgCCLolnAQqRnLVOvvLACyxg5a5tL+I2u/2W5fWDhq2PKzBirBK6PYgyJLwABz1qrg8NEM+Z8/KKuSEa3NvkaAhpZnFHg+DOWaNmojhVqRhoSnug+MZOvKQEMu4yq5OnU2pG3zObfwA9r3XWapnu//RXH0T9OrZGSaDNNUJ6nOw1cf1I4wFyLLHqblnWEXFxw+nYGfngLs1wUU4vTd+J/bgzPjoxOesyZuxnt6sLo2PV+tAMq1TKuwPRQsEpErOUrBgWVpB3K3ZJifHNf9OAF3jsY0Ib6AMTPaJKM5HbB9kRRptnr0edbFVgSnQQ39ymPJG3AV0wFrchMqkT/C1vm7ZeIVX42keXnae7d4XYQcYwpWXJp8Aih2w75lCEp4RJejnnKglsHmY2kJ7IFkmiOoEjOBwClzuRjqvalozy6eOXoz7asZtSAr07TN2vPB0Lkv0ENsKZTFTmq+6Dy7Z3RzIa08RLs9n9J/32xS350zcU0dEOACZUH6Y8e3D8Sf1RVVfm1aJlscW/aphYgkfv2zD11xiUiLWwzG2D65eRmQTcQp6rgTajvogoEmOWCgvG1llQCWnS4w9+Ci6SVPZAFeLD+cxVSO4Tdgq2oJjJdOO8Ngfr9rhFBKKWC5FEvcUV0m7lTI0jA1isfHImNo1qAccXFxis+288LQRcCqnvcJuEMZD/XwcqbTaUDWFo7yR279S16yXhiw==
  template:
    metadata:
      name: minio-credentials
      namespace: mi-carpeta-medica-prod
    type: Opaque
