---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup-credentials
  namespace: mi-carpeta-medica-prod
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAMVyaaM7wFl2TAN9j4lNTS8qHhRSGM9GOCMOa7A6gKQDSZr7SVZ585yCClxhevgR1PKmTkg9pjOo8b4kRQTPMqsSRu0ckkogmjE+vm1+JHM+alUKrM+SMdN7tLaSfiTwDolz8GYVV9WnASYInvFzoafdyN70agDj/QHf+sbFQGBclC68rsKoUpIsjOEeiKaNr+ojjI9dHDxAxsWtgTf2xfAgs3yQmk1h+arkvnrn6mdQMKitlkbQlq4HAqxlcZ/zn/vjUlWC8tT9G0ANzkLn2DZnYDtbBaP6CXxHcTLO/vrMyVV/PICsGhoK7QjiveRBJME/OWWpo+j7OUZFFS1jPv63z3QUJIFYbtj7BTn0gkajEl1haZndShHZOttzP4V5pc5lQHyH4BQRals/A2TDqSvzm/LlSJyi37+T6fxWrJC2vxLGOSHD7O212RP2zCNhsCwJjRZTjfnlQ/H6ZmjLmtP6WJtYTVxEJqZWeGFJFU0udsdKQeKbdQQfEAAgOlV0CezaKOQXWEvsREEJr4C5lRqL+jnJ1+c65JOxqrr/K0hZB7eUCEakedf5P1BWJJjWEb/gYcGb26y3nWOGCgtlrotyNkELga7/zvR+gOzNNH2ldEqeNVp1D5xsJyCTpx2m2eZ/wQmVNeeSOqIFPa2BQqHf/mHzbdjE90RkIHCUAVD58JtRcp6ap/3J60SgRaUM+nprsEow==
    ACCESS_SECRET_KEY: AgA6wSreE/WSm5fIpr16kQnqiTStLQJxlnCsIF7ihDFgmyL4UC1x6tZpywZ8MHCPAOdgZok6C329W45scCzIuGPAqNxcmufxwpim7/8hcLk1Xl7+QF44vQMpMy/LSLLpIw+cMSsL7EGcX1T7Gf/Zb7sfJ3bonvtdfuT0523H14vbiqXiSQou4F4q/c78tIEYh1zDA4aBMENc6hsrkobQeLm1pWCePoPdoEcwFYSffu2sCFTG7BdPOnj5imf650JHYlMr4EaE2brZFvjpMkjSrxI7mIiKeW5Tn8/J7kj7L3W3jSdXf8hXY2AAN1Ez4ctEvWSvN5YUWJwY92jGRlu96PxOux17WViHgeEpqAoqBKCW+3WCdx0qHaHY+xMvJCdi/JgUGj97qe9BASnXZzTtsNvojK5L6U9qKE+pBcYz53AiVBWQQdiY75lj9dkH5aogHk8bpE9y9cTsV7RkUxPOALJLOg6mjGwsYtmfGUySEOdGjdcswcWhSwD1i/W3mw5PpDCC9x6xEGzePRw8xX/HmGqwqrIdmgA1J1VbdWK8woe0Cw48UclO0ijAhA50Lphzn9YxNuaIw8c7mIQiPNEC6N74FoMN3rg5w6RQZwuzXu5Me+t/IHGJXqTTDCK+HabxdoY+bsqfflUj3TU0LwM3/DKFi8XJWRhRyyHVL8Eg1+CH6UusaRwQqX6UQnXLkhmhWhMlZiAVgTPlwhsCj/YtNEqT8QP0C27BX5F2l6b1QUegnlp69KH+HYPvXaBT84k7Tv4=
  template:
    metadata:
      name: minio-backup-credentials
      namespace: mi-carpeta-medica-prod
    type: Opaque
