---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: mi-carpeta-medica-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBQ0UBIklHTCXTr6xMKixeEePo/4CIGwRyUymx8Rvd0OrpxxrkKhGEl4NbxmXyj2oxpmJJz9b79NJXBCZ61XDGucXB2qiQY/RiIPzXnECuK4ycY01VLHq/EaPXmI0PRF8WoxizyDwrFEcm9CiOnmLdliGzxOwScwQA2oOKasF9ztGhGAaFMn9yh5faDKHJ2JjrxQEMaaOTUpSIosRZA/2XXpKAeLvwOcTvoLAtQaKR6fR/2cRsUWZlc05TZvmJA3CMbf9/f9RdPNvw1d5xAIkqoh9ERkFwaIdtXgV5cbyCBkgx+XQMaRtF4oTnd7TQZ0u8rNHQqMSM6tsKt9LtGrLJpIv4QERNFTLBkW2+qAWaUOMHnB91eFtM3tr2iWMyg7wXviMcJAC1JnERekNxtayFZNNDErEB5k3kQgzresG83RbMPJAXMHdDZ+wvmvxTtPsU38aCgu21cDqTf0JMNsEnDEQ3wUTrMb2p/hTJ/uZZ/13kpMy3Gc1WYAeBIQfyg0BCI2lATUN3DEWYEPPbQsPIFmMBH/urwWVwdQJf0f/jMFBuLfRb8E5j6BtoUxuDmJB0wqb7/4oU0gL7vyfkRrItwHyEYx0jXH5jVGxwB9UZ/3zSPjYFpGd4KsLVnRv+P2KesqdzF+QcDnY/ZnhaYImiZussCJAG+LWtUWD2fb+8WJD9HZaOJBm1ILpow4LnSlsArFyGvDvsnGigzArxgBzDIo1uKymUKCYcgx6jOwADCC5km+7YRo8yj+XPcUwoPCyeK9keblBsqVe0rpAfouleGDr5jkBorY2t8plzyyGDdpDFyQqzTSOh44zpCuPzwSrx3jorb0gohFLlJsoB/MwWrO9YbchmGY7hDQhncmoIYwCxCPULJpMf8pJRHIUEJkbhIPr3jrD05+T6TiEl8Q2kIBvj5epXSacYmTB4xF+fRfQecVz/R6ezSfbZLRxxIM6qQpHEnbhef5E/XSYxJSqNsznLiQVB/k9j2JVP2p73xmoGW
  template:
    metadata:
      name: registry-secret
      namespace: mi-carpeta-medica-prod
    type: kubernetes.io/dockerconfigjson
