apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-helm-chart-value-overrides
  namespace: registry
data:
  values.yaml: |-
    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 20Gi
    service:
      type: ClusterIP 
    auth:
      enabled: true
      htpasswd:
        secretName: registry-basic-auth
