apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: registry
spec:
  interval: 5m
  chart:
    spec:
      chart: docker-registry
      version: 1.10.0
      sourceRef:
        kind: HelmRepository
        name: twuni
        namespace: flux-system
  values:
    persistence:
      enabled: true
      storageClass: longhorn
      accessMode: ReadWriteOnce
      size: 20Gi
    service:
      type: ClusterIP
