apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-rule.yaml
  - alertmanager-config.yaml
  # Descomenta una vez creado sealed-discord-secret.yaml:
  # - sealed-discord-secret.yaml
