---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-resumelo-webhook
  namespace: resumelo
spec:
  encryptedData:
    apiURL: AgCbN/Q3jKCFSAMgCL32Ckxw4/y4+/GGGNynvSc33zpEU4fWsoIMRPtdHeqpWjMBzvLvLC41ON0QfATi5b7xZqkMzeU03Ut6u1TLDu6xWA3B5dw3cven34hTzKZCN1aKZFSNOQ/TWEvMbvty2x9xEMv37oelLkfa8+aUJu75CIkQtsD4At40akxgCgtIjKOSbhXvhuiXqOT/oCa4eK3+cS8f6zpof2ydSF2LgT3OdW8pYal8RbU4IlS3HZ/36PVV7/Zo/siZOxPywTr0Cq0j/wE/72bT5JRtZShuJmk/ULMLg9twhGaIcddq4VJOQgSRQNpWgqwE8HhZ5TE4t4WBG5Ub6PjExN4mIYG8nQzzrXfWEXTLSnKXB2/wLI1zMLqJGNHz/SbQ2lc8FRoCGURVnqU7UaJUQCo2p421MD6nbbK2HP3gtuc73WvSf5/t0dW4LHQCxOwJeQpKOOz8ipf4OXUluM/a4Ck4BWPXrhSGQcFiBacNxQpp/VN1U/cF8PsjZUX8qT2p9iUFULlK04o292IJBa30B5fT/dEUQwQAz71keIvcN5suk/GFvqxHvAXvD2FrnsEWCBBoyxVfxtJuWD3ugnTi7KbWlBjJ5HHO3VLNLwKu6fsx0/qNKv8Czh9dW8iVVr0iXOXfDIuKfqoDQMjqXpnmLo8jZkmL/m1/bo7lSYkAhXWeYvqkq5Xn8PIHE+z75TvpR5EpHh6ZM/3OWW9G2EgfbVUfSpd+VxHM/ah0+K0cIdrA4BmQ6Tm3T3Yhtq2lbn2YYGbqMwxxbWOVq7yi5fV5hNm5prrtVEQxQh/1TuPCJ4iiejjNa7Y5nzyvMujDxD4wK9pTVgxipLOI2k626RW5zrFi4MnX
  template:
    metadata:
      name: discord-resumelo-webhook
      namespace: resumelo
    type: Opaque
