apiVersion: v1
kind: ConfigMap
metadata:
  name: langfuse-helm-chart-value-overrides
  namespace: langfuse
data:
  values.yaml: |-
    # Langfuse configuration
    langfuse:
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "500m"
          memory: "1Gi"
      
      ingress:
        enabled: true
        className: "nginx"
        hosts:
        - host: langfuse.yesidlopez.de
          paths:
          - path: /
            pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: acme-issuer
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          external-dns.alpha.kubernetes.io/target: "homelab.yesidlopez.de"
        tls:
          enabled: true
          secretName: langfuse-tls

    # Use external PostgreSQL cluster
    postgresql:
      deploy: false
      host: langfuse-postgres-rw.langfuse.svc.cluster.local

    # Redis configuration
    redis:
      primary:
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      auth:
        enabled: true

    # ClickHouse configuration
    clickhouse:
      replicaCount: 1
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "500m"
          memory: "1Gi"
      auth:
        enabled: true
      persistence:
        size: "20Gi"

    # Global storage class
    global:
      defaultStorageClass: "longhorn"

    # S3/MinIO Configuration
    s3:
      # Enable MinIO deployment (via Bitnami Helm Chart)
      deploy: true
      
      # Storage provider to use
      storageProvider: "s3"
      
      # S3 bucket to use for all uploads
      bucket: "langfuse"
      
      # S3 region to use for all uploads
      region: "auto"
      
      # S3 endpoint to use for all uploads
      endpoint: "http://langfuse-s3:9000"
      
      # Whether to force path style on requests (required for MinIO)
      forcePathStyle: true
      
      # S3 accessKeyId to use for all uploads
      accessKeyId:
        secretKeyRef:
          name: "langfuse-s3"
          key: "root-user"
      
      # S3 secretAccessKey to use for all uploads
      secretAccessKey:
        secretKeyRef:
          name: "langfuse-s3"
          key: "root-password" 
