apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: langfuse
  namespace: langfuse
spec:
  interval: 30m
  chart:
    spec:
      chart: langfuse
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: langfuse
        namespace: langfuse
      interval: 12h
  valuesFrom:
  - kind: ConfigMap
    name: langfuse-helm-chart-value-overrides
    valuesKey: values.yaml
  - kind: Secret
    name: langfuse-postgres-app
    valuesKey: password
    targetPath: postgresql.auth.password
  - kind: Secret
    name: langfuse-postgres-app
    valuesKey: username
    targetPath: postgresql.auth.username
  - kind: Secret
    name: langfuse-postgres-app
    valuesKey: dbname
    targetPath: postgresql.auth.database
  - kind: Secret
    name: langfuse-secrets
    valuesKey: secrets.yaml 
