---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: langfuse-secrets
  namespace: langfuse
spec:
  encryptedData:
    secrets.yaml: AgCEkFL20u+UDBuxZxEiPugUz5JgJyReT1NUXZmIsV3n1aj7KwAV4znNDw3shkElNjhD7yio6RPgxl9ydCYnylLlTc6yq5MzRrZiJja1XKjgaI5rhpWdpAiUnUoLA4mHX5Lmb95t0CJNKoSmIbBSmAtnO52T4cpmjVL4SMzDUFxrziJ758xH91fwUKb0pLccaOiuxGRtD5R+TRfDtrdRM1fldR4aSVMWuMaN2BbiS4U5Q0us/rvxLfKfk1KDo7YzAyg2Fxm80DZweLMrK0aQL69cRCDk9eulC97kQsBUfHabhVUnIIZxP4Jrz2DIPSjDIygF/uBep469MQes3iiiP3GSr7kaeaD1edsgLWxQzI/d7HM+7RQA6vFzGKf6XDLvBw5RrNJ0FpQk1FcBI4WyWCeKPsDPrJ8nCWdfWZ0zVj0BWG8x6w0cBUNZRrVUOdNUSxqlQdwgVmNfQbAVSjoGuC/RiGLv2+DNA3qobWJ3Rv4eyo73GPksuK19UhzQPZUKp3MMBA7yHEl8MX/Er3g6yTGyEJrshgyby/MiHSCWP7VDrsV3F+KtqUH9i3EM7Qs/AYJATslQy7YtH12D5IF99J7yYx8BivS1XeTrNOOGkW8zrnmjsApZ8njyep9VQCArmhLOdMUGDCFxHjOrKp3eA1dC85o3nFq+gKhtV5cDMbCU5tyE8H2WqMG7IAo9IzIwUl1Qmj1odxPgFKQ+2Fkc6MnRpjioOohp/Kcfl8zkfkTcOrtpWvxSa8EHUJ4/0CA4vw11ujje3Sna3gas++CSj3HKy7hqpHSuRW2GNrymfA4rH8jZeC9dAYRf0zRH80FQpHqlPPitoyyG61YBhmyDY25otg1NmgdOW7t+I12fuqCeuw2WRfrRonO8O6OCSapIjlJ8qlp5hGk1eo4rJD8EihC2rtRLu6rjxcJsGQrYCgpJGAiiVTp6JVVKE2u2wfmSKiVoC5jDV76KBsFsyoRe00WNjg8cvDEAfGxhe3c5zLDIGsSYxxzNCQMCRdgT3Xk2nyVh7o+XHXUbFqtbRIZ2gc158bej6/MBG6Wnu6vqdlJW0W5cxNdfNq+nXEwFbRZVXdx5jIqn+P6vpwuvYXRZ+H8zJr2Ko4h/RVLuyKr3a9eWV8KKkgwhlHiYkp7/Ksgjt9stSf0jwwhssoHVW9bw/sf6JF/5AL70WuMdxpJ4IORXJkThDX0IamQuk/hX/sKHjl4yH6bG8NYjfUNAqvTpPLTZF9FzCiu0AaptDG9HklaI1tkWsCOTmY87AQ8bBUVJLabUOIQMsHI0dGJXazdiEVJJcux7ZyqZpMhrWB7OmPWFHYKztt7NCQ3EdbITiMlPmb1rT9i8
  template:
    metadata:
      creationTimestamp: null
      name: langfuse-secrets
      namespace: langfuse
    type: Opaque
