---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: langfuse-secrets
  namespace: langfuse
spec:
  encryptedData:
    secrets.yaml: AgBC0NikKPi2f5XWPTyB/2e+eBvWavLQJDnmLGmkDW3DN2ArbraUpJwCzNfCZeFISLnmth/sg0hcS6Umk6VrJz6y9vcFAFfrGcHA61Ms6EsdKz7A7qMClnvzrDTINZn2hkLTUwZINHNzEREGr6PIobJk2Khnbb/3hqqM31BsPUKIheH84Xd6z73/NeV4Ay+X23sJBr/QcKfq3LQhwuCy7yKcLZOZ/Zm+AY6bYlMOc51wH0FUzhTy7eG8+Y40yDZt18zDxfYmk/ECm7caIUD8ZR49ND/gpc6/fFqe+TIKEVIb+3excG14jwQuTjeIDxWHLRKqamh+wo9ArSv8NooRnlCRqTiWTEqkxaPH1EhnBe2BEolUU35139VNW3P7j8cSo7o4qe9PWlZu0SRH+pIOvaOsz4aQlj+vqOSP3aWcaDNeVECn9wVrOQuqz8hGiHmhu4bwCPBCqpmDslqf/vTjDDjsew+yCGJedGKDeDTOyGX4UnPyGDGQA59EXVFk3txtcvdnyGF/CLGLJgkF+cjWHDaqEo+XBCykzImEmWpWF0Tu5flUUrkz5Be1feeTzo3MuTZ9M69xAl82LaOjgeBGrhwbcNVtISoOlAFpV5nkBAHawf3DXQxqNu1SdcRp7axB3qQ7AYCJ50g+XFmrJR0RwuC8zvMlu++TvGkhmQDHaI6PF1SC+62gAjBtZuZTLugVAqBpLhhUc0QxLAo0JRF/pyJRw7dFmOgm8QBguLN7IKRb/VNyhHVWISprbPS8HDQDxSzu5d9/wd7TFiKIg4zeqw2lcsbQvVImSag658Ue95ED5ILavqraySqlbSGsaxfGRcKEmMPLVrXIHW6qyWBTOXmkcuNbIf8M3XHyiswil+qbVWQ2Yvpyqrf385y71Du8F3FPWp8bgEfsjJ22pgxaTVBr97ndSl9Hh/uq2JkoYx1sxCxil8Fz0O0z3N+MBliJj85Aw+cXJtJFDAqlpOwo2KEX1hHDoCDZjkQOCa+V8+4nor0eOdTs8BygViNMdk7emTlZSlIzHIYpx/cgmHqJsTc3Ajcy7t7Yxa7d9ATW6HhShKPWVG5S8HWQDH9eMQ3Wm6Hlw8+vxL+b7fEp4YGzC450vbVGsvCq/jAvM1ynD/K6ZDiYOoxnWtdQxejORQL1XWteI+XHpGKO0WrixlYlb0NyHE/q8JrmAQ46IXXEnv2iHemFWJPA0+WtdwKPLEbjf8DlPRjz7VKytGD8/JMcrp19+QfhSOBllbT6c3g7Soc3pZsDpTRsKKXSBM52/wemi5p3UboUUzXX7fvHu4knMYXXMLtPDvv1G3/cL+BiYgdTi+Rwfbqkvt/7P3cNQ+dXl510vx0K
  template:
    metadata:
      name: langfuse-secrets
      namespace: langfuse
    type: Opaque
