---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-helm-chart-value-overrides
  namespace: flux-system
data:
  values.yaml: |
    adminPassword: admin
    
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 10Gi
    
    service:
      type: ClusterIP
      port: 80
    
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: acme-issuer
      hosts:
        - grafana.yesidlopez.de
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.yesidlopez.de
    
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          url: http://loki-gateway.loki:80
          access: proxy
          isDefault: true
    
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    
    dashboards:
      default:
        loki-logs:
          gnetId: 13639
          revision: 2
          datasource: Loki