---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: flux-system
spec:
  encryptedData:
    adminPassword: AgAXB0C402q3vtX/sfqQsRw1VqLQQtfNI/IBEJY3y+RtSj/Noy9YzepZcF/hyDmxVdm4oGDxniaH+1tcR/H6UgIYfujt6yxZhqu8qmKqDXTO89YWcWz/Hk6AvFScFu3ZCZmXb+3fWQ3lxWErdkzd51jDZUf/NJ1yi2sTcQq+8MVPOsR/OXbFcnNqddJlwAlR3QaEuiYgNW7ewkPUe96xZv/XInd/RgdZoTrBs0LWewsh7L+bsl9xJWV4QVZFP+PzYECiMEHd3u+X4y68pj18PxMkJToA0I2BJGyvrDO7gD4P7iKAdkOZ906MHMYf181OyWcyvlGGYAHbCahUWlmz7C7i1sQvCOMc8xFhw/DZ1xpszyuGGv65EN3RdvUPCzLAagnCyI98uh4J7EHQND/nn5c3o7hsAoHRXPJ2YV2Jc4TrC2gI0nZ4qFI1J8xxsGgDAkzwS3zOOdMnGdsYJy83PNtNmhPfqKB5d7RhD8dWUCloowMtDbR26LfvuITfjSAsMruFUKhpO2GOi4Vddk8cTogpvAQicu6kwvTz2YMb/0+q6YLaG+KqJUAm+Y2Y3NBTYbTivJBEblugOx89OfKDA/C3CJsdOcFlkcGqLbsrtqpORkD1EhdS5qnQeOucwvHCoT9hepwepREr5xPqnoJHgf8alELgOLLl1xTDFAC8Rz95ed6z9Mqo4S2U+TV/W8E+UAFgfwudys5TgzDGbhR1z7xZoIizEQ9esSbx7cqehOX/Ww==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: flux-system
