---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: flux-system
spec:
  encryptedData:
    adminPassword: AgBOSArYvZNHQs5Ps0030o6tPl9198ryPLW3VrVdz+9b82TIOb80Gms6fXCF8WxoKTiS5zPBOT9bnihFVr3kB0ngguPZe9LKUAqwwRYWlNwkm0b86Ec1BfS7gRTNyVqv+gsM4V9y3Wk/Ciau6zlfKh6O+acl8Nz20/R5GKF+XSK/WnqlvfhggcebQNzREALJduHdSmY7L7vwEBEnU9Gso+OQl3S2vkFTN2ZsCAKpQX7qHEdmQfcjeWpEpBB7Y5KCey+vcofhnLi4CVVfHQs8X7VRYLrI82gbCLYpkPCyz/Pyl2Ycj9nOG16CbtsyKMaE6GLlnqtgkX8kVoHXpm7yF81zJU6E7+TrCqcVvJpUE/lsWtEfkEPTQlvPjlHrJU21ggb8s4QLdQaxPhY0wqZxvfIMQravQSNfbOLXLxEQ58YcLRQ6XWbwjbiuLJZFXwhArrw+OusiPET7VwUPPP+ZlqXFP23pdckMxH1WX+gesxQh8EuRhnZn3//RYkR/Z3vICfJEzciXpxOVg/vllFY8ytdInxbj3lZXmnMF3HOpGYOmA4aOviJA6wbN2PNTqcqOAhJT35S7gG1a8fF3DUd+gfK1VL91bybg+dLLb/EZ/Gd622kcsERJ44O0qG2yyn+9PLZJiauszoyEwHGEx4e+ulChyGDHA8pfzzeevaDPuP3OIhWRUNHrkyI+1fGDt87nRD3iyktvtDS9P43l5vV0
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: flux-system
    type: Opaque
