apiVersion: v1
kind: ConfigMap
metadata:
  name: test-app-html
  namespace: test-app
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Homelab Test App</title>
        <style>
            body {
                font-family: 'Arial', sans-serif;
                margin: 0;
                padding: 40px;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
                min-height: 100vh;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
            }
            .container {
                text-align: center;
                background: rgba(255, 255, 255, 0.1);
                padding: 40px;
                border-radius: 20px;
                backdrop-filter: blur(10px);
                box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
            }
            h1 {
                font-size: 3em;
                margin-bottom: 20px;
                text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
            }
            .status {
                font-size: 1.2em;
                margin: 10px 0;
                padding: 10px;
                border-radius: 8px;
                background: rgba(255, 255, 255, 0.2);
            }
            .success {
                color: #4CAF50;
                font-weight: bold;
            }
            .info {
                color: #2196F3;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🎉 Homelab Test App</h1>
            <div class="status success">✅ Application is running successfully!</div>
            <div class="status info">🔒 TLS Certificate: Active</div>
            <div class="status info">🌐 External DNS: Configured</div>
            <div class="status info">⚖️ Load Balancer: MetalLB Active</div>
            <div class="status info">🛡️ Ingress Controller: nginx</div>
            <div class="status info">📜 Cert Manager: Let's Encrypt</div>
            
            <p style="margin-top: 30px; opacity: 0.8;">
                If you can see this page with HTTPS, all your services are working correctly!
            </p>
        </div>
    </body>
    </html> 
