apiVersion: v1
kind: ConfigMap
metadata:
  name: test-app-helm-chart-value-overrides
  namespace: test-app
data:
  values.yaml: |-
    service:
      enabled: true
      type: ClusterIP
      httpPort: 9898
      grpcPort: 9999
    
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "test-app.yesidlopez.de"
        external-dns.alpha.kubernetes.io/target: "homelab.yesidlopez.de"
        cert-manager.io/cluster-issuer: "acme-issuer"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      hosts:
        - host: test-app.yesidlopez.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: test-app-tls
          hosts:
            - test-app.yesidlopez.de
    
    # Podinfo specific settings
    ui:
      color: "#34577c"
      message: "Welcome to Podinfo on yesidlopez.de!"
      logo: ""
    
    # Resources and security
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    
    securityContext:
      runAsNonRoot: true
      runAsUser: 10001
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
    
    # Monitoring
    serviceMonitor:
      enabled: false 
