apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-app
  namespace: test-app
spec:
  interval: 30m
  chart:
    spec:
      chart: podinfo
      version: ">=6.0.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 12h
  values:
    replicaCount: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  valuesFrom:
  - kind: ConfigMap
    name: test-app-helm-chart-value-overrides
    valuesKey: values.yaml 
