apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - postgres-cluster.yaml
  - gotrue.yaml
  - gotrue-ingress.yaml
  - sealed-secrets

namespace: mi-carpeta-medica-api-dev

patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: mi-carpeta-medica-api
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: mi-carpeta-medica-api
