---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns-updater-config
  namespace: ddns-updater
spec:
  encryptedData:
    CONFIG: AgAUIIMYXyQMUr62TKGaIgrYMrQTwbgxlVceixEmWrod7mKRRYObkwsUu0UfIIqJmutvqFBUQDT5igAjhxfmhXYfmUkYW6hQqRe7x1VTrZrqZyYtM7eatC17+6KTTezlWRqdvs8p9ZA8x58I1xIC91uef1LDYpHvFWkQBNpYJhAzLPopa7KXO2mH63pOZYnAV65hNNTycln+TYUlrvL7u0FIOng3ZMfK4nmi0E/FjdxcergsRqT4vZXJ4nJZmGbBwTM4zkp53bxDStDFSJA996JqwWylLcVH/qdX2EXHuyskD50XLzBkZuqOiPgpvsAZhi62bEKc8fi8pR17yyp9pxygEObwwvgf9ZEy29Wy5SEWdPhfe0XQggVLNWascwz/hsNExMRXQEEjk9KWVczZXLH4yuDe2YIFwkSUiLJkvcb8nf1ewEhMAAFePvY7gzbtXolXQbZ6Zyn3gK7LbrSubDnzT+FftsJS9FMos/KtE9Bsi8r7Fd9nmqJEnbq2m7flRUG4+lq1YTty+BjdIEiT4N7czXVKDdgPnxgmyjA/Xj+andTJvkiI6/SWS9A7ZXHCdy85MhXTR99oRtUflDXLhUdNeM+636doELs8ZcSbz7NGBdUToFA1mBPBRDBRqSf1pE8TepQbgGsPTUE+SJpGA8M0kNsy8GsA6IbjIwUVw+WheE5BpoIUnKSR+6B2lQUX1CZMPptUxm1UK/xNBa/kM1f7nXNWykYTulKEAHvT2YytpE0iBM9i8gWc60uBhGojkyhm925GAJbFS2DRg7qpvfgPr8DVhuW7qMlUsfOvwXw3sU7WfV8IZ7p+u+vrotQDrKroGGj9oI2tVi9rQf5zQ7otqasPb0H2ykdxN9Hr2eXDOXWDYO3j1M4UZTjI4oX0q0HFPNE0aY52ikgYPsAZW8fsIQc03K+tsN74xGCJvyFj6+Uvk3/6pv120IWvbuoFdtQm68XoySMO2LJ1CurB0qHLZzjOtwTLbbH8DukaTdqGzR8nuWJWFZxmFfUb1x6dMuUvpqcLsjbdOif5nHHa6B5ooAicYXVjr4nbsBru9gEhLdZ7YULwoN+B1RI3JFkeJlPv5ITuiwKjZz8A84O5iYiuTOptEsqIgHR9NC9j4ZMrecfgxgFyKk5104+C9woeF2YcbYs/ZeRhDXlAXdd7CohSwQqNipLqE+0=
  template:
    metadata:
      creationTimestamp: null
      name: ddns-updater-config
      namespace: ddns-updater
    type: Opaque
