---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns-updater-config
  namespace: ddns-updater
spec:
  encryptedData:
    CONFIG: AgBzVTlXoC1N5/wXJV9H0EiiTUHpJ/q32JpYFPXoYyIUBbcdRKgvSTySUdMBML+ZvwBl1adRjm7I52/n3vVFoQdPZuohpGuOz7cbMbfqXLexYVRnH7oQ1GcSLV/575tw4Or+JV5rH14QEoWlP2r3wlAaa52WCR+QiJtoCpIy/8CfkOdJlY1BxbDKXLhsLdcEzfQS8fbveWbdPcx6VQa8zY5rcSky5py39eEe8V43w8t+QLjJ0K1h79Gv3DDT+7pZKwhjKj4hA2BC+Dt4OoMYqbfvqLjSx352DL+SqxxES5lT/235/jCjcaHATPQFYHlzfR/PvBK60HzU2e2vTt/rx9v0bO/4DpbndvthLZWxrcq/c7MobbhH2i1gQIvZEsHVpoRQG6Md1UcsVQ037gThu2thPf1U6OC1YOq7Y01p8lm5xr7Pel+eHf1JYNhGWwxPSTLt/7tQJCcDClK/1TnVBl5vLKP105IJt06r/bkteXIM2TpasAg+7+ZxH9ZcLBO52KkDYDrOLiK42rie1Nilxwi6SrtR2m+lJjxBMlEAjDSHjFEyofpFGLyfLGotJK0X97StP1qKoKITZMZJu+ZxZobwpA7vlo/NlwVValVFkllWpn7P66Aktl4ZLbKYreKh0ycmVNaL5jgzEQnj9ouxcOaFTmWERwwQSR+aY30Xk9n315m34CqJE2IF0kzf0WtLM+F591Fha9f22eTd/ddCJnXxLr418IUCfdrt4S0NGf7xmbaBsV5tHhjyLVVTo41ErdkjXyIpLUFwYi9aMgYENJ4j8WGoQLobVhw4LaE3URruVePAof6LFPNvwIpD8UfNvYKM0WM6VJfxJuk88E0GQFJ4AwL5pcE2yCBSHvSbOnOE7NAYSlXmi3aatK39Oz4e9m+v26cNDT7ncLuzx/NdA2D+I87f7I7JjN+ql1OkhYmBYcnaD9g6qBywxoLAFkHZuraJEQZmCnB6WSHcX2sWB6OnlI8iprJ1DxUBl1MiV+EhzwmGmtPmwSvcz/mH+3Ws7jsT6bckPCmY6sCINsr1ZoDfYOTT8deYhtAKZmrApRbX4bU3OePvdfHH5TIZ5s1IbLY/UJykiCWJ5hWot0Xz6oj80u5RtiyPyJwslEABycImsjnU7SI2qp8LItyvm9stgS1zYkHy7dSGnO6354DqpUJDyn1zihUa3LR17ZJ8LCV0M/iFNaGuE557+J+Kd4eM
  template:
    metadata:
      creationTimestamp: null
      name: ddns-updater-config
      namespace: ddns-updater
    type: Opaque
