---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ddns-updater-config
  namespace: ddns-updater
spec:
  encryptedData:
    CONFIG: AgBdAG487kQ6+u8WAhtrTnDpEpjEXiaKu4fJJ8KGejWB4su7JXFTreApTPXtIYn4lLJkotgmzNmvgsi7ir+xywXDHnv96ghV0AKUX+02KCqXG8ViZCmRQwcG62HNZQF0Tp11EwD2pfIq5YbN62GSJUR0CS/m5yKSZE9ab8ZC/n4Ez8eGIqnegMkNxzhOX1M85MlUuHxth+SR7VLeJZiiH2R0Wy3HZWPiKe3hucwYEBpKOzelZixouv2FDmel0QrTTD0GOOKQtNI1fOc30YHB4eqmvevPbVvlHOFp3jtl6NFNg3+B/FUbDlTHDcZctYJXbdoGAwvZcWGtyiZ7ljF3xWVjtLND7dJDJduPeDnscjBQejlZzbdbbkpuXflMNMtNO8Y6Qy+UVCKl7qbgmUdbNDS5QSUpyi3TBOA3R9Ue5yreYh2w2d+FNjTRRbg00LL3xXV+naA7u7fBCIBE1dEJ4/f7op2krCaysdPU5vAWes6rihM7Srz874eoRhU3krLKY/lNljW3qUdzrdwoAAybnNgudZpu3DQ2cGVM2samJMRzz9mPj/rYJ7GnOD9WvzrQb8jOq8POw9cdsJeMyHFG4r3WFXgsc53dk7lYeoChE1cFRGi2xPQe4ZQ+Ed190Oi+sew8/THkQ22FSp8Xhatau6vKDAM5LHmeb5GKPoZs+RAVvzV5wY49kE2Z74upl73DTHkjCj1zDfdemS10Li3L6ftK5duRwMGAfQ34NWsAGLFox67BtXHy1e8Xu99AuyEXeU0CASMyMgtfNj582Im7a0KRdywVbYzAggWoELF3XLsk9Vw6bgh9HcprleTEDP5/zMyziH0i3zlqzKGSsfwSoVMoNBCQgfndnfZgeI6AXq85z7diuDj3LBIV9F8IW0uPRQedMkBIMXgkvjkL8WD0ITCY7ZAuFN/MJZNwnJXRrZtu9RvpeT/e/E0Ca68GwqKJkaQJ3XMme68AnhAq79rWnRdKO2shYM3G9OHGBd4/zBoETV0p6b0XlbtAY74haBLicA5eL7SyRlvmfYMuCUphw6ogLsF/KnHd83sfnyWCKlxxuwIS2EQ07F1M0cUoGEnLMaYmaKaoe1OrZEscaBEOD/YjFLW89DLezJ+Zd2PehEb5r0kqoyVM095023HFZg75hmZlcEUPlEVhYgoVqNR0WKvJEI39Jx8HezGOP1SQ+iukrWAGBI36S+HbQyaKJfpD
  template:
    metadata:
      creationTimestamp: null
      name: ddns-updater-config
      namespace: ddns-updater
    type: Opaque
