---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-homelab-webhook
  namespace: prometheus
spec:
  encryptedData:
    apiURL: AgB+cyZ/FBl730eazpR8kTgczmZUN9H4l53uApOZIhp0X00L8IYTFPy/vZXreCa8edEVkJPSEdttMY8e05KGKQeU0zFCOZNuL/zsvEzVv9zqza4YSmGOFqc1xinnRkhMrC9RF4tFFokXvlV45ew/74W5dT1w+o5bfTqnF6NYVRoa6RGwjb4bYgnPQ0ThL6+n3QHTAoFq+ohr1qoJxYdB3nYyuATnG3wKOWdAoozzvdmJ4+WGSura0bt4dX+F0plIA9KEr/ca7oxj9yjMGzSuxPzSORII3BO51rbi6doklz1c40ux28KElBJLHaFg7RTvSCb09sCBS45Jw7rF4GcWNimErPUeIWTy9BgQlF+Cbire231VKsehwKUPeSleE3Z/FNbbD5XigZnP/CyVopgDsEaCLr1ab8UqXhAu7c1/qoB6HRXvkK2Ymk7pFu9F2mb6aXYKaSLK0/mxZ20Tl2RQg+2RI3TSB19TCcE8wnnAGN4zDwHUbZZZOH4hzcYLLqHp8p//Ddb8j2eUt45skvuTl72+0QrXIbkKLqYGsB+0pvUHQkLtESphoBjyxdGFGM7nEfB4qtCT8S997XqAdP6/fP+LgdC2fOCDwmZuCTrGdobVxYwBJ8Wu1vN9XAq378A6h8U2ZEkobMH0imR/Q86inUAo+cZ9V07BlQx6YLKshOdNewKM9he53MZ8kWNJI28XB4CAoCYIxREnAWkvLSFCuAUYsFA7p3gISW+bMiLoNW1vkJ2lk0VjlB4OwyiAUxFW7+4KKamuiGSnV9N0P/AjYTTRYW8lV7/b/5tBL8RURdumG9+YadaFzQvMrC3PD7fzEwwUYOsAYKBRRcZtFA/BxdXtPB35wRfXmH7C
  template:
    metadata:
      name: discord-homelab-webhook
      namespace: prometheus
