---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mi-carpeta-medica-ui-secrets
  namespace: mi-carpeta-medica-ui
spec:
  encryptedData:
    API_KEY: AgBk+YUgxPIta8g7svNhlZbenvHD4ms1GfbafE2ylKoPH6gw7ec0bds2/VOR2oCF+FfMRnxQ5sDA4znXVT64wjdMYOC3CN8m3ws4Gh9aXbLvQLoLZLOSJz2BdKT6HwxpgmHlSeq1Ad/m9yC560+AO3bL6DWCUWliS7K7UiRu5qcAcBPwKSHhB3CozyRl+rX2XDVkSQS/GEkZPdPnxFevP1LcB1/B69ryOkUbraIQyeccbat48xtu6DFGXJkogHMpUotZv8oAGv0U8v0GFJtqWOAPscpU/HX6Pp18Mb13qU5vsQcrCUvw4mBpbysEAxJuP5mYwiCzSDY1FC9u5z5QzuNrLX/M9doczhmd4CaEuKJGr72/3BJ4607A7IFfJjU8C0c5yYbLlBpDZ6uw7eN0bxkL5b2jBgmHNVwvosmUXNo/J1gSJnKLS0hMavJ9Ck0ftFnHaMebigg2h0FbC2De8/QtQtuihrI0j/zwKzOeelC6qeFOtMkJHHCGB720UWltNt0oJ1IH/lDu2ReQtIx3vdFiodMho+sYMwrcxcDu5Aj/Jg6EcZ6fT14CWRWEfphmoiqtEubRmo4OHtd9Bd3AtOyN3xLWj3K3Sg31645CoIYxTXIPBl6caQ0V9f+DLWbNWvWGCTdk4lPsDnHls8hXWZldyCv/HsAtVgJ6myOdjYZWoVie/5nSoRVphhOv0XGb/mAYQY1svVtYTeJ/LET57Wk9OhXHO0fVm8vR4oX5D4DT7ZUEdE402aN213Pa
  template:
    metadata:
      name: mi-carpeta-medica-ui-secrets
      namespace: mi-carpeta-medica-ui
    type: Opaque
