apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: public-status-api-readonly
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["list"]
  - apiGroups: ["kustomize.toolkit.fluxcd.io"]
    resources: ["kustomizations"]
    verbs: ["list"]
  - apiGroups: ["helm.toolkit.fluxcd.io"]
    resources: ["helmreleases"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: public-status-api-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: public-status-api-readonly
subjects:
  - kind: ServiceAccount
    name: public-status-api
    namespace: public-status-api
