apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: porkbun-webhook
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: porkbun-webhook
      version: 0.1.5
      sourceRef:
        kind: HelmRepository
        name: konnektr
        namespace: cert-manager
      interval: 12h
  valuesFrom:
  - kind: ConfigMap
    name: porkbun-webhook-helm-chart-value-overrides
    valuesKey: values.yaml
