apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - configmap-helm-values.yaml
  - sealed-porkbun-api-credentials.yaml 
