---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: mi-carpeta-medica-api-dev
spec:
  encryptedData:
    rootPassword: AgBcfTpqpOTfoqyn+XpCQ2AF5mdjyykqIJT554OpgiLBE3gMhEwhCvWOfTlvyx/auL+YloO8NtqOR2/sJZG+7UAYY1eomZD5la8sIYMO+pssO1HtO5PmngbCSS/w0RUEih3Mo0xKH4TmcTw6ojcS1qVN4MtIu56EGmkznvNgefy/x/ZhkDUZg3a4Wq2GOGpCPjjozvHQ1eWUpe7oI5b8EcfynIIBkI5oRMx2hFydLk6/3XOSdvCDtN7J61hBx002TprP3zhsNZBvAhbjFJfqR3WH1d4oaz1SQJ1114ebv+3J2yLWW8z62FXFp/VTNTf4+EEJ1LULPlwEViXtT4gzf6aBGthrvXyPYllhx4m8VEGn/K/unLxtxEjQJlgz3f2P/XF0nkGJe4ZdegtLltVSkGcklnojzqX0Tsnevd+rGlKeuTu5wcL1plGhU8ke8PRbJmJ90YF1ySoBaJMVp02xOvBsMESHsLkbW0XuxA6tKew5V/T2Mk8hq7VU3FjAcq0Uygyn0Q5JnmGBKRfz+fMOx4X3dlBg2NZiwoJsx4+XTTcZgcgvMqogUq4gR7HEi8zLdpgEe3yQwagLyDJcd3JYeo9tvoypmj42GbCp+3VhApf0LEEaAjF05RhOc5m5jKFY6OCHWCozb7cM5bjikiwN/Xz0ANxnIsgaeLgsBgCAupGtrqIzRsqTK63jGUGAjMyvx1Qtf7Go/6+aOFmG18QaW+9y0S72ZR8/Qp0X9RoIWcEB3u+zvNMMgqeCPfasX7o2kGY=
    rootUser: AgAGNCGXqfBPvwvafrmkCMYz5IPO7CWbBWynpuWI0rZM0fL1Xb29IoreHDc0cNpVdoYFQM1iNNAY0q5XgJjJ4qt2hp2R3QcpdK3fEUiMjKpw5V8q5OUIpRr7lkUcZ4tYTmkP5n2ilinWYQWlvBM+v29humXqrx97k3swpXMoWln9OF1gNDGd3ucIb/2nxx7CGEQLL3+5kMPgbin2qTtcIRW4AGoS1wADsiKprYf2RoUYF9RFbukkRr7Gpc4yu4M9Y1dW9QPU7dC9p4Yl5oRD5IfPjeX+gnwztnjvD2VxY//B+bg/HuOuxiZ/oNmTin8RKzfxnRz7ln+nfhMXtekg8Pm3sdWRx/CXn1i+HostXwnG7xlHSP7l7G/5w0x8VExSDHS2vRFJFdJdFqiw+Cg4EnhexpvYRA9lkcqxPK+734VgMoEwpipVHDwqlYYniTsaWWH7Z6zst0QaBhp4nezflq50KAerwOdxSFWH+OeyDW0cuJLLqPLAHrBNR8XYnxsmqYlmairO9zYQPONk32gaq+At5lxl44RqkiZJvW0Gi/G21axHHDdAmvtJ8rdA1mqFrtE0qW3mkbFP6VFELBa6/r9D2fCY6OpukB+6VCN6k4eYCs4NjS1p1v9DdyNxf/KMQWVMZUxYZdrDiF2V5ojnuq9x1TmwnGyqbnRJsVGYWvPPdaqtaCEAbn9qUQq2s9ZHKX1HfWeCSQ==
  template:
    metadata:
      name: minio-credentials
      namespace: mi-carpeta-medica-api-dev
    type: Opaque
