---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mi-carpeta-medica-api-supabase-secrets
  namespace: mi-carpeta-medica-api-dev
spec:
  encryptedData:
    JWT_SECRET: AgCbtM7C0jfFwkTCV//xZlOBwMzLCdfnILQXzXe4nOFs12gNpMSg98aDO3DDx848Tq0/zy40COXD+H7lswBSaso+hkbnISdCGG91dNozR5yb25/I04VJezgSSZkQEU46H3XzjDliN3rlsVtlu1QyLs3vKewZdgSdl/jPQr243EHzPR/sG2Q3IIQ5Wz4wRha6wAcH08rLqbRB6ePFXjvJ+OuyN9d1m1obKqfwQiOvOyQhRV9tVuogxViu6gI44uYh2yZ9GKpzjbYs3gJwZ2kCl+PWxP06T4q5uF3uefS6kRO0MhJCHCcXUFkw5iI52rE6MCzYQ0VCNkoCpWgUMqbVcgauAZ9cu6eEDs67sT6QXgg4UmTY8vnAvpiBrO9WsBK1yy2NEdC2fIZUWxiw5EiOeW52NeS9VmZ15jwbuQTi9OGxt/zDPXr/MReg6QVl0osAY2bC9MeZpOCIn62sFvfO2bPrQY+EKuuA5e8hVtUbq4Sia99PyJDwvAKMMxOoaB+He5f0AaG7VeT+VYxEKhioOAaHSMumWrd1s7zez7qoQPmy/oNbR/qfGpGDztZX4VZPmWaB4ri48r4sXg5nfXNfdqCmqMcH/OkVWNOgJYYtQoihaeM1aiV2slSvEylbz/YImjm4B7W2OjwGxbnwa3OwnOlLrFYJ/A2hiLuy6WxCjJliGoSH4jCgQSq7S1ZYZKqnC0MHYnlRomLlXDyhTILt3A1ec9E31Z+OxXH7gsxF+5pE2RUcPBte9vzU0mrqCEP0wKXRR4I7FcKC0ObmLRRCjyWy
  template:
    metadata:
      name: mi-carpeta-medica-api-supabase-secrets
      namespace: mi-carpeta-medica-api-dev
    type: Opaque
