---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mi-carpeta-medica-api-gotrue-secrets
  namespace: mi-carpeta-medica-api-dev
spec:
  encryptedData:
    JWT_SECRET: AgDXVVNsN2SKT/W68s358vyvwOAa2z4cwwRLXsbrBkvCMTWgs1qQE5miwSFAdVhBT4YN6OKi99MeNEt/7hw+MGMOXuyki+E0SKozQ7pKmjCtvdM3QcwNvKy+QgjC9TSq5TRa8xKllz5iRMgykoPEYQicRSqRHP5FqrqNeR4q9I1rWyKHhGRW6jw3x/xEtIyxtqyAT8OJvoCyWLoTCS3avcio8zhWYSX5ibrTzwxOe5+ZtYi7Rp0uaZPdjmmL5pOC4xMrbv7iRN0Ud3X+RQz8w8ds/in1vK7aOraf4lH/UAepi5G1j+czOFQHjIB/6hx8vkdS2lFQImjL2bv1ccNkgn/KXn/VU2TAznhkFA1dsn2wERHBe9ZusIS6bPcXu7oh0SogbqG9KO1d/1dS9mSdzjoYojTJ/H6BuZ6f4eXt9Vukt/Fxsu8L0M3zVONH0sCS2L23PeJCh5dZCa0nQXF96g8rORQOgJiLaPvPVNzcoVosfmbpFsIVxyV44sKdBCANBxB4MKNKhtVwYZpGE9ZGemZallEpfvLYC4xRPC9AvGaRZCBo0GH4uJBoQgzOHEeFYAaBTBc9aNWKCTCv0KJIifacVLt7rDEyPuVMxisJfovr6/HIxqlf6u2f49Hv8von1xgpt0uNJY2SPhTbrL4okPUb+FMyH+mWV8Kx/YXLI9h8KjD9gM7OYu8689wD5EPsCCPmVGt4AedPV7mYAeCqzeqyAijzmTp+bXrnuB3gp7HBbbhRkt36r75qDO9RSQj0gnryvfU9H3GXoNv0LBzXgAgt
  template:
    metadata:
      name: mi-carpeta-medica-api-gotrue-secrets
      namespace: mi-carpeta-medica-api-dev
    type: Opaque
