---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: mi-carpeta-medica-api-dev
spec:
  encryptedData:
    .dockerconfigjson: AgDBhbL5vHQjZhJPhVZdmOx/DZ6SxWOhLlMkP15tjh5C8drrN+f58ItBhLxIDlKCFSfMPQ9nQ+JWxpdmkMnU0kp8gzLRMcNSS9IhqWrGXEUAf7ASA/0WJGbppO59zIcDl3B5AS1p75zo1qyN58jDszXqAandZouf0/hQRCsKJoHuHumTKUf8qTMOHT98H0O6iaMv2+E8ChNoK4P9JB3KVrqwEsN6mkwMGgrltTFJLVFyG+XABTh8DbvkrXny++QVe8J3LE+LVB6wROGpxjKYC3VFg4SAL00elmECq/MG4k4JwZC6s6kAJqq+Q8d6ieK8V4b5Rn/xtTDDkowaoarc2Fi+X1MrwfezXTsgXm2btFYO9bMLjkfJqnFjmy8SpRZ/3aPTOnAQhSMTin8px2JsyejxaF/mB2tuSnCwVXhPoX+NoCuT0G8hbwfJc+AiNzZU81F2zIMdL7FHYpDPldAs8ooLid+W7A0Ff5orJFg4t8Xgcc6KfUtGLOVNbFOucC1dKYkhy+e5e+WwdMT8xMt4erZ+6Ql9xkreQmQJ+eFQvKKQ8wxCAonhYKZrcyzuW7SWWdfcJ4cMTlC/9UUmi+T5c7H4//mSm+JckLKJ05GhHL4PNro2MCI3sUUL7jCPzK0T91suIY1gFd9XtYuvQtpdnOIYGHXtXtQhHRBvUq0k5loibP1XFvnlR1SVzCoFtqX6KA/Jqatu5mnvUCs4oL6j56ZBOyqQAB/K820deMOccCOP4NlU5bZXlnWu4IL6PC80rrDDgc9eWUtug6F31xqaxrqfVXHtzYANC6kfExOo/+S6kzwTGnVqHCXdw1zQCNgQ7nZMMYYQX+vW/NyK8VQEta0WE70ArfRXVeeqqV1IXWZGfSWmBSs/UJxBtFUfc4G7oPMqmhbfulU0g2glcBaPpgKs7L+Qp92DfFJ5OaK0f8h6gjQhWAYClzaq3K+xXkHHXOvQjpkWjPx8XMMi+Z3hklsnSeq2dSbNy0mBBjbrknLrnRkw
  template:
    metadata:
      name: registry-secret
      namespace: mi-carpeta-medica-api-dev
    type: kubernetes.io/dockerconfigjson
