---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mi-carpeta-medica-ui-secrets
  namespace: mi-carpeta-medica-prod
spec:
  encryptedData:
    API_KEY: AgA227aR7NdO9TNaSOBTG/JV6yv1NSq2VXdFrTu0dfhdLaOnkCw1dw7VejqQSVRHYd67lxKqhAKXOxMFCkPOHE2haXD8cEbetahKf9OIVPdpmuCnfe+W4FYKOWYedzi7djDQicDGGEC+51x47AvsFiyFzav6dTLvK7n6VTkZlgCJS07Btyan8k1dIixUBKXf3240bEdfbTRRLXwaKlrAqEuIZLwKyxrs+NmPN53zCuX6N1/B/a4trzA3xsgNmQ74H7GZ+InsR1fKCD2OvSTTDBlV10oQK+Slg1IBO8MQCnMv5OVzJt01AglUdRESYl/5p5OGgx1opi/iBzWBz+4GWSMhz38O/ndHMT0mH8MUlrYpsVQgc40yDx5nqzTvviQtv8lMkOeEndkLcjnXV2+TBG66QxZpt0A3PXB/k8u5OOCo3qXbGgLjyJ2UydQBdEkUAchs7GPZThsfZw5yf2XQbxLcv/Dcj5KQ7QwfmuShmtqyff8qPH0LDW260KOUWxQWW+PTSmjLNDrcUEtoq7FSnNzvXUhGVtQHsnLj2phzjK9mQA/KZ3ZmJs9HvSHuLZi7fNW0/PyeWnm5yZdErmSW3b6IVvL/80tgdPWbrcFQiKmwltyK+JveHlatzq7RmSMjSqaSqr9WadKF+9YYR7lIZ2uAqX2kkWXG/4BciQqrQo7SUpsaqzKqHOm6la9hCwwru2UcMqqpLIP3ijCEn9U6D03RvO+kjY3YG8AkHuDvF8SjHJp3q5Bu89naJeta
  template:
    metadata:
      name: mi-carpeta-medica-ui-secrets
      namespace: mi-carpeta-medica-prod
    type: Opaque
