---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-helm-chart-value-overrides
  namespace: flux-system
data:
  values.yaml: |
    deploymentMode: SingleBinary
    
    loki:
      auth_enabled: false
      storage:
        type: filesystem
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
        - from: 2024-04-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: false
      querier:
        max_concurrent: 2
    
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: longhorn
        size: 30Gi
      extraArgs:
        - -config.expand-env=true
    
    # Disable SimpleScalable components to avoid conflicts
    read:
      replicas: 0
    write:
      replicas: 0
    backend:
      replicas: 0
    
    chunksCache:
      enabled: false
    resultsCache:
      enabled: false
    
    lokiCanary:
      enabled: false
    
    test:
      enabled: false
    
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      serviceMonitor:
        enabled: false
      dashboards:
        enabled: false
    
    gateway:
      enabled: true
      replicas: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: loki.yesidlopez.de
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: loki-tls
            hosts:
              - loki.yesidlopez.de