---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 5m0s
  releaseName: loki
  targetNamespace: loki
  valuesFrom:
  - kind: ConfigMap
    name: loki-helm-chart-value-overrides
    valuesKey: values.yaml
