apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: umami
  namespace: umami
spec:
  interval: 30m
  chart:
    spec:
      chart: umami
      version: 7.4.3
      sourceRef:
        kind: HelmRepository
        name: christianhuth
        namespace: umami
      interval: 12h
  valuesFrom:
  - kind: ConfigMap
    name: umami-helm-chart-value-overrides
    valuesKey: values.yaml
  - kind: Secret
    name: umami-postgres-app
    valuesKey: password
    targetPath: externalDatabase.auth.password
  - kind: Secret
    name: umami-postgres-app
    valuesKey: username
    targetPath: externalDatabase.auth.username
  - kind: Secret
    name: umami-postgres-app
    valuesKey: dbname
    targetPath: externalDatabase.auth.database
