---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: umami-admin-credentials
  namespace: umami
spec:
  encryptedData:
    adminPassword: AgCiU86wOPcx+8z6Qcnmon8wdYQkXFlPv9VXoveOVnegG1O6LMO9bmOSSy7nSTh1awHVeIxtMEKp0RsMb6HukGDuT+tXbsjPrv+put3qN1JKMptGwJEqrII2cc4hQRHI4Kn5Po0ZFmuSY/qsCSHd0rNt6NuazJjLdnBOX6qr9Bguazl92WnIE826wdntMQvs+NZevK48kzYjtUZzBp0uOi4V1XeMM7N4iOQ1fiof4BUFKrUpIh0Q25ZYzNmlZZKkylu8KXZbGFGXF8Nc0n1bs6hyv2aC/BUCuTSvESkD3cXG+LtGMbbthEfHr3Vts0Rw7PJuAY6v3GIyltsPI3KE0QxiNB8vh9CGd4wYyw0NRwK1Mf2umbShykTXBkaoZzhsOJekGNOkeFScf8U12DTXeqWZr49B74bStvUgD4GUk5dJNxwlAeJOvpAIGlHUcgfZB6C0QBpvI7LMIt8MUGRRZ5Mz7CArxJRp/yhPuKKUonafzOJb1uiSBCJNshilY16BRK5bIPh2d7aGrjiiNHaZRnd1ODcSaVyNH1A/Wd/sGIorJUIhSS9zcL0CJzFiNCmtioe757IMoiiSe5BNPkBUGvCD+1Oi6VGdUb3Nb2vtxI8VzBZKmNXey33tvtH+IfABBcTsQRNJKa+mFlEqXm4n9rWvBE6ZBzFF+U0wLIzuhpTAtFtfwLLK6Ald1KyRQzRTQdPqBDuvh2v2XG3zSqKI
  template:
    metadata:
      name: umami-admin-credentials
      namespace: umami
    type: Opaque
