---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup-credentials
  namespace: umami
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCFmQ9j1+f6O2pULfm2eyYZs4Pbk8OlmP1EruHMUNYMxOZxpxYaGvJaCGi0KhaPcAxA+Wtq2YkPPJUIrnE3A/sDoGu+8qpD7PUmhkgJmtiOCMVpf7EA9RLnnJfJzSenp+BZKf1JWNSaZ0zyfbq0IaxIDTYtVvyjBsZY1uUrhBRsuah0lrHiyLG/n0j3yq8X7sq/f+9FJ2et6eFNLUVFOATa46GG9t3qR5TsGCEFtnMEt9DBEpL8aVD15qSCZ30PgURRmwqOIg8KpirGbg8I7JmKdfNlEfZfB9QuNsces5CxzO+aRytn9Qymw4z0mW2YH+AduMidb0fl5jsoE9i293lbBzt6gLlZ3NeafXIm06JaHmHQJ3awmK6K8qb1JOhhQNLqLy33AkYa5D+9d897kFpwhurPOk0d9qNADVOnJXKIxVI+ZpY1BeVMatAGblOlTR/xItVoXZD5u7L4m9JCzqOGyRIwFSuKbPinHn6+mFyiBTUE0EwWvZpWw7B9KYFuNp7vnix2mDAgyiy8omZ0nBK2s8WzxTEBBYTCqH02lCtCh/4Mv5ScG4nE8K9wuM30g/RDbEFK6JCo6sIqvqq5oc18SMq7EOSKHobQJqGJMV46xpwKSt4aYuplh65rJH08kAx6g/yF+TfmcB8+3OahKZDicm0UvOcvpMcvf0asjjDgh0I8zkSibcgxc6znijBmzJecpZ5yAQ==
    ACCESS_SECRET_KEY: AgB5kEasZvIRVv1TI1w/Cn9FbZfylUJ9cRnmbV7kKCbMHTNLgKeAl6iOrkEZOrEcFQdMV4L5FqRVEY+585otEU9Hk890SqFCYnBUjrrVXd2HhvUxMp10+myN3WRDf2VexIDmGCVZiP+0WD4/wq/YeDuCVtFSLbwx+BAXAUxzAE9dTeGYmF5Ychk7PQW04eVg5uiI/Vcz65BlrmBdg7CfaMn5a3UG3p36vxNoDmI7dVHdbcZQVYN4pUsE4dYNfXoEAo0elDwmd3z2Cl04W3t1tJM8ZZdFE4PwvZ3Xmfgx2lDO65pz8figfegJsdhpQSUgFZHecIRkqZyxyN4L6K6FXQZYZnHdrsFy5nQsKqSvpQm5du/0NW6l3KfkqfKRLYSpSoWDcwL9movryjHGMqaqC3iJXICrxqjOKHv8rMU1JLn3lEjQF9UaV7QMj6DHJyr0v1dZt6Gvwtqn6vBW40f+BW/HWWyFr1HLIvh6Zdw7DwZPoIK+xZMmby0nDPhL+LmJ6S15w5e+noXRVd2C2R9jplUmAdT50Gus8Gjmbl4UcBHqlM+3b1p93OkF42cdTcl2vRTKGQykpUHCF03ta021f4nP0oZspRr87TQAEB8NccAIxUWMZ4T7qM5aEqsv+SKOcDHptkVnC+WC0u9AZaH0YXJ7dJi6OADT8bLQYKR385gt+14xAFVZ0Uh5As6eaYOFrYZmcSKu8Pl8rFFNKrHGHQ5SdrBzwf1iuMJKXSqrWqRJeLaUxCHjzFHX59oJYZu7ksY=
  template:
    metadata:
      name: minio-backup-credentials
      namespace: umami
