apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-helm-chart-value-overrides
  namespace: external-dns
data:
  values.yaml: |-
    # External DNS Provider Configuration
    provider: porkbun
    
    # Logging and Monitoring
    logLevel: debug
    logFormat: text
    
    # Update Configuration
    interval: 1m
    
    # DNS Record Management Policy
    policy: sync
    
    # Registry Configuration
    registry: txt
    txtOwnerId: k3s-homelab
    txtPrefix: ""
    txtSuffix: ""
    
    # Porkbun API Credentials via Environment Variables
    env:
      - name: PORKBUN_API_KEY
        valueFrom:
          secretKeyRef:
            name: porkbun-credentials
            key: PORKBUN_API_KEY
      - name: PORKBUN_API_SECRET
        valueFrom:
          secretKeyRef:
            name: porkbun-credentials
            key: PORKBUN_API_SECRET

