apiVersion: v1
kind: ConfigMap
metadata:
  name: external-dns-helm-chart-value-overrides
  namespace: external-dns
data:
  values.yaml: |-
    # External DNS Provider Configuration
    provider: webhook

    sources:
      - ingress
      - service
    
    # Logging and Monitoring
    logLevel: debug
    logFormat: text
    
    # Update Configuration
    interval: 1m
    
    # DNS Record Management Policy
    policy: sync
    
    # Registry Configuration
    registry: txt
    txtOwnerId: k3s-homelab
    txtPrefix: ""
    txtSuffix: ""

    # Node Selection - Force AMD64 architecture
    nodeSelector:
      kubernetes.io/arch: amd64

    # Sidecar container for netcup webhook provider
    sidecars:
      - name: external-dns-webhook-provider
        image: ghcr.io/konnektr-io/external-dns-porkbun-webhook:main
        imagePullPolicy: IfNotPresent
        env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: porkbun-credentials
                key: PORKBUN_API_KEY
          - name: API_SECRET
            valueFrom:
              secretKeyRef:
                name: porkbun-credentials
                key: PORKBUN_API_SECRET
          - name: DOMAIN_FILTER
            value: yesidlopez.de
          - name: GO_LOG
            value: "debug"
        ports:
          - containerPort: 8888
            name: webhook
            protocol: TCP


