apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: external-dns
      version: 8.8.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 12h
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: external-dns-helm-chart-value-overrides
    valuesKey: values.yaml
