apiVersion: apps/v1
kind: Deployment
metadata:
  name: lulo-cms
  namespace: lulo
  labels:
    app: lulo-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lulo-cms
  template:
    metadata:
      labels:
        app: lulo-cms
        name: lulo-cms
    spec:
      containers:
      - name: lulo-cms
        image: "registry.yesidlopez.de/lulo-cms:v20260510.154206.f5ff4f6" # {"$imagepolicy": "lulo:lulo-cms"}
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: lulo-cms-postgres-app
              key: uri
        - name: PAYLOAD_SECRET
          valueFrom:
            secretKeyRef:
              name: payload-secrets
              key: PAYLOAD_SECRET
        - name: S3_ENDPOINT
          value: "http://minio.minio.svc.cluster.local:9000"
        - name: S3_BUCKET
          value: "payload-media"
        - name: S3_REGION
          value: "us-east-1"
        - name: S3_FORCE_PATH_STYLE
          value: "true"
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: rootUser
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: rootPassword
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: registry-secret
