apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image-automation/
  - monitoring/
  - sealed-registry-secrets.yaml
  - sealed-payload-secrets.yaml
  - sealed-minio-credentials.yaml
