apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-registry-secrets.yaml
  - sealed-payload-secrets.yaml 
