apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lulo-cms-postgres
  namespace: lulo
spec:
  instances: 1
      
  bootstrap:
    initdb:
      database: lulo_cms
      owner: lulo_cms
        
  storage:
    size: 5Gi
    storageClass: longhorn
    
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"