---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup-credentials
  namespace: lulo
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAR4p2QJmJZbLmDJ4g6zkFS2tj+31JJBB2o+oMV4ga73nsn/dTsFeomX2XmFVOqn+3PLoQX/czk4/06fRRxvOzJWzQ9/0aGGB4m4UGQSZAEUPGjOBqPL32i3EZZ9cvKQTd7XsENxNzwazuTAOuGxs4J3zGBzwe8MM8hszv1o87uNXARGKYF9Oo/EpLounhCDYjyAID9L5mSN8nDYjUuHx216km0vqxdhf/lmghaQg0RKYiLJxTyy4CH33WfQL6r0YfKyYran4tEL0W4yBEo5QzWeWQLICDyagHKy615hPuhKPCQj/sM9PZdoLIgtj7KY2wxK1lK7HRDI1leL42VQAQq61igdtr6xkBUPrL4DbXL6JcS8n7D7+nCmx7XFKEY+JNtaFfuYEDqQKpQfOqmWY0HZoig2qIPwPMQLcJ0ngZ8qIH1X1c64SKC3QuH6oTtBhE49wFhXpl3evzZSPOcRH9qEps+ZEgAfWZFGBp5YHiU5dmuaTMRQbKk3BkGzKXzzbwEReCDewVdc9IegWRBZKTtuo3rDGJ4rCDUiFZOYlUO0ff8qcOTx6JuXKmmcOpACibAlmvOycKbtR8JafOw468miY2hS78yVvYHwhDj0DOsw6GvS9eoIfalsS9McaA8fWSftPAOX8l3yrxgi2bLgluS7GCGvujAP9MlVRHiwCBr/SmWUqFDTkHG+K9Msy5KWMMVYU2GgQ==
    ACCESS_SECRET_KEY: AgCq/Q3F1zorBvLkf3m4Ln28CtwPSOZKRQqlMEAcxhKsAGKVmPX0ohpnzLS8CHBsu8AvbYTttAU6prtOEkoLiZ86DOmCfh+tQMKqwLBVWnLCwMdom6kwjt9PvC+dLSn9jWzLGXFDWrdTNU1gYOubL4HOXn/AuV/En+XiAM+hLFezdLAFl27hp6rsUyZ+CL6kLQrxfT+YB3O3+YCyRMmK0qmJAc2byBpyI7yFme75v4GWVAConUvA1lt6GdXAyZQ9tVUba747i2/bz4y7nPvihy/lAov0LvhR+xPVe+dY1I6NKQoYrZcFcfbU4pbzebwPLs4DdRTCLQN/ufFv3/ZNyjXjve9olCa7hyzeALvNoU9fIRmcbyfrAlr8hdCIJYUOe7hyf+WlWcHU1OQc8//ySzU6B4ER4/q+Tww4AsVWjbRES5a0E9ozAfXnpOFh8AhYhzPK4Zk2mwwsCYT/oJowtbjZ7NJIH5A40QAJBwG2aWv5AY5Khs5E9IxKAhbr7aAo4mVxSX9buCUcyj+C2pH2Jn7ZV9+uocmiteKHUpNphN3e7Bc0Xex27VRM86jHvKl1EoyDY12Px1Iwfx54mJaa4uITm3P0CnhN5NbJAqttfv/haZZx7s4nGI/N8qD7qRvGdLF7FKRBKKeBZqIRmt9J9tVU+qp8YBgqkJNWJt5eekL9eSGLIH+pUNgUTehbpWWZEGgJMOPm45WidH4jf3vGG8moPfUXgwd61huGJ9EZUo4hPaIscZIKbqXQggMRM4hX+pU=
  template:
    metadata:
      name: minio-backup-credentials
      namespace: lulo
