---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: lulo
spec:
  encryptedData:
    rootPassword: AgBaNMunFGXgZKKiejK8UXT264fLKQwxydXk00jLqcXXdOmsFWBA5wog8xEHpPIJf/MSTsXpuuUeintZHidBIf9+GkpRa34ReIrEupEP3ZQi93wZ8cLM8tRZLuvrVpzf5iO+1PTuUJl96j4jFeR4EsCnPC8Vcy40OTpoaemU5y0gB0BmL1cVpHYolxTCIffV83t5IksnJJJa1bCKcC+Tm7ZWeEG2hTLnGLmOeL8HJK7n4utj6NPeX+6lBiYhG2zNQbkHMYrZYb+EXhuKQIK5Zih5arXyoHWA0RMYxorTN7oDv8YMVVbDsTT482P3aBCtxw+x+eV4eOWcWVNhJQjlTtjZEU/5xOdF7avxiHEyftQNK7Yh84RwnMp/LnQAIl1AIjhfQW+ZBI0ARZUcPVw1XkLP7QpT5v162dsZ/HGJRN7urvfItpcP4C1erMybYD6jCqcllkjTZmzOjQJtYYfZE/7UQKoNH34feqOSEUbYTeguDey4lGOFWt65AK3uYQhhBUhf63fgwt9d1OBH+t6QJgjdQ73Z8z1KBYUSRy3EqRyEjEikJQNfq3xN7cruwIoCkUiP2gboAtCXrUz9BqaUZlXiMSTp6LoA4EzmcxTT5FBh/XWhXzlcd+JoRfmebRdKnXVE4Al/ZvqExhF02yYa1QKVs0yLY98a4t75MWiCK+hF85+eEOj1WpvR80o9Fx0OQxFQUNX4+1sfQRxsaNKhItYdJ2ngmx+PpjUIx+9IPPigAIzNbkB5SRe8wgFY3PJ3d4A=
    rootUser: AgBLkvjcZiqAzaGXQcVJ7HL6BbK7+7Vm7NKBy9im6aXZNKr9M3Op++mRHzyUfvRXpaT58jws3yobqfA3JYjnOa1X2pUo6OooRZNV4VFLjeK+XyRGGizMcUHDGXwn7YNjvFNQdlunDhfXjl35BpuTEWgfIEgkzlP/d2kZxNguWwepd0Rx9zq2KLhUs0AzahsDQ+zv+/ybNxzWhRE9ZQIIOEqF+TT6UmD0qCyObBSp/vkb2xSo5crfu+GmUmpJNrRPBYOzraDgdEHyfY7LnnH8aD419GLeLNDEi5CNwQxQAxlQtHe3xHlMDzCJ9FRXXjj5jtThaTNy1yrhg2z9ju9kPkLpyTQbCGqGeMDbhAxacar1OWn7gkWFxHU+fBVpaWEoPQGr77pe/9IsrbeyAHsEk64Q0oDEcxknMPC5YNztNOE8Rv6IxkFc6iLSjspy522LfI7EwNNhUCwoyPvGNFBfI1qNjp/PUUsr7QRVtgPYbM3jw7fHXyJ5r6zNVjpACvzKiydJmalaElMY2ZNrXASWMljSspvZl8nAZUA+7s4fKdnZkp799r4zlPj9Yeuosu8MoFSxrTUXF0RqInX8FAPTX9tsRaXhCelzLZZwxcyE3KvUwqOXErY1WZV6ErwfWjcpg4fLmSABHZb66Tw8huBXnHEZyOGKkn5K43SVxuEsbsi4hLVXm/Op5x04LJO6N5PaI9Nc4JoUJg==
  template:
    metadata:
      name: minio-credentials
      namespace: lulo
