---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-helm-chart-value-overrides
  namespace: flux-system
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
        retention: 7d
        retentionSize: 18GB
        replicas: 1
        shards: 1
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
          requests:
            memory: 1Gi
            cpu: 500m
        enableRemoteWriteReceiver: true
        additionalScrapeConfigs:
          - job_name: 'kubernetes-nodes'
            kubernetes_sd_configs:
              - role: node
            relabel_configs:
              - source_labels: [__address__]
                regex: '(.*):10250'
                target_label: __address__
                replacement: '${1}:9100'
              - source_labels: [__meta_kubernetes_node_name]
                target_label: instance
              - target_label: __metrics_path__
                replacement: /metrics
      
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: acme-issuer
          external-dns.alpha.kubernetes.io/target: homelab.yesidlopez.de
        hosts:
          - prometheus.homelab.yesidlopez.de
        tls:
          - secretName: prometheus-tls
            hosts:
              - prometheus.homelab.yesidlopez.de
    
    grafana:
      enabled: false
    
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
          requests:
            memory: 256Mi
            cpu: 100m
      
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: acme-issuer
          external-dns.alpha.kubernetes.io/target: homelab.yesidlopez.de
        hosts:
          - alertmanager.homelab.yesidlopez.de
        tls:
          - secretName: alertmanager-tls
            hosts:
              - alertmanager.homelab.yesidlopez.de
    
    nodeExporter:
      enabled: true
      serviceMonitor:
        enabled: false
    
    kubeStateMetrics:
      enabled: true
    
    kubeControllerManager:
      enabled: true
    
    kubeScheduler:
      enabled: true
    
    kubeProxy:
      enabled: true
    
    kubelet:
      enabled: true
