---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m0s
  releaseName: kube-prometheus-stack
  targetNamespace: prometheus
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-helm-chart-value-overrides
    valuesKey: values.yaml
