apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - thingiverse-mcp-imagerepository.yaml
  - thingiverse-mcp-imagepolicy.yaml
  - cults3d-mcp-imagerepository.yaml
  - cults3d-mcp-imagepolicy.yaml
  - imageupdateautomation.yaml
