apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: thingiverse-mcp
  namespace: print3d-mcp
spec:
  image: registry.yesidlopez.de/thingiverse-mcp
  interval: 1m
  secretRef:
    name: registry-secret
