apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: laura-valentina-rincon
  namespace: lulo-demo-landings
spec:
  imageRepositoryRef:
    name: laura-valentina-rincon
  policy:
    semver:
      range: ">=0.0.0"
  filterTags:
    pattern: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
    extract: '$0'
