apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-helm-chart-value-overrides
  namespace: nginx-ingress-controller
data:
  values.yaml: |-
    controller:
      replicaCount: 2
      service:
        type: NodePort
        # Commented out to until the new router has arrived
        # type: LoadBalancer
        # loadBalancerIP: 192.168.2.100
        externalTrafficPolicy: Local
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "false"
      metrics:
        enabled: true
    defaultBackend:
      enabled: true
