apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-helm-chart-value-overrides
  namespace: nginx-ingress-controller
data:
  values.yaml: |-
    controller:
      replicaCount: 2
      service:
        type: NodePort
        # Commented out to until the new router has arrived
        # type: LoadBalancer
        # loadBalancerIP: 192.168.2.100
      metrics:
        enabled: true
    defaultBackend:
      enabled: true
