apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: nginx-ingress-controller
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: nginx-ingress-controller
  valuesFrom:
  - kind: ConfigMap
    name: nginx-ingress-controller-helm-chart-value-overrides
    valuesKey: values.yaml
