apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - postgres-cluster.yaml
  - sealed-registry-secret.yaml
  - sealed-minio-credentials.yaml
  - sealed-minio-backup-credentials.yaml
  - sealed-app-secrets.yaml
  - sealed-supabase-secrets.yaml
  - image-automation
