---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: mi-carpeta-medica-api
spec:
  encryptedData:
    .dockerconfigjson: AgBI3zW2VR5C7NatruVjwUyonw9MRs2ryWd9A1z8vLkAKBjI+mFmf05AN1Y6vjWeYrNNoM1jVvfQaTKEMyv6f4E53Lb0hWnEkxfRYLB6owjWgXYdGdTCYxVnNSwX4b8/SUt9NeptSmIJ1zx5RQJYl45+IOTKXpTuEVYe4HSovEZ0sEPMQdB01hSZN9MUv38FBLET4c9qVQf3M3lr5wxnZU9FbVdbIoKAPUpm1nHxsXuhPSKriBRmBPHZg/UlzJQg3engJQZ13EIn2szZCnbpQ52HET3eZPltkY/2cEdyMS3U4Xm/kBs2U0vEvpruUgWYXBZFfEQKg2l17u+XFgcaHwaPJ3tCP6J1bOBkT8MkfsiXld1PWxjl/8YFl7RwNZz001kvx6H1KeAxO6SghqOS8v7Q0g9DxYokEnToSMJTtk9+8ox14P2GFBg8+uSSzvh8i1wX+qk9MBrzdUD/LtB+WlaxEfAnOUSnUyBbTnOyK6KS04KhOoS98QFEkP2/m55tJthHSFs4G8fDfiUGYOvheqpzRQdmvgkygbPnvJqQgMwIl4QlAlCja0I6hAyy3uE60F+5TH9yDiAMq5pEfywZ80Jt2NeZg4AHn/yRJH6UQqfnWr56JIldBWPL6pdCRUzXRrTxK7BKzaawYWVeHcRf+6t3217I1Q7iqbzIils9xB1vRhV7eF+9rTya3VUCmXR9Osz7+shsrxRfe2biiTaeQ0ump6s1DbZS04D9FVcMTINZp+7lvKAHgusFrVGNneC15J2SwxGDZe7pF/mDudagJn3eJo0iNwIAhCHlQEEnjHU1um4H+SaxykVhefZvwQ4OIMoertx13A7JiZxR0V9j6qh1Ly1PmgIX5S8Cphakc6b/5lAUzHTxYvhDwRsw48Nmig64ap3hVIyNP5dDz2mwYTzoD7qJU71J/VSFBn8lxarhm3Qc99LtxRfoUuwDEONZENPLAPmUN1P5IrDydMohxP4tr844DTerlN7lt1z2aN9dtT+B
  template:
    metadata:
      name: registry-secret
      namespace: mi-carpeta-medica-api
    type: kubernetes.io/dockerconfigjson
