---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: mi-carpeta-medica-api
spec:
  encryptedData:
    rootPassword: AgBHrCtwXlsi6qlARUHBJXwufce+T9UaG6No2cPAS9w8MdoDnEUGGLOciTJYA1dANE1XlmMbj0HzUNL2R27m0X+Rz+4SB44dGM4KjdsfAOKKP7F4c7F3jxYxLybJdvPwifR97DiRadpinJNfO5VexuOfIFYcnP2BonOEQhY+Qga8fBLnLbAzJlJ6C9i5eKfdAIPEj8H1JL02ecVyAQAitgRRv6IUPYb1WobU+WKxHWBZsmiBHYmtJDoSaFTkHuyNIN459HeRm5oWte78oR/x5H++oPhzhJmQ7wgchthAAw5CkM1kcgD3YMAkqNU2RIoeL5B+Y+pUUQG95TG0Xr0nXLYHkJT1B8JXQvcz2PUb/cmKQv4w05El5E2AbVMMZnwoXEK+quczobajkQmCZMGa4hebDOtuADnca0jLB1hpTEn+fVyzOwME5XEt4wqm3dRCBwqBnOlbdqoo2R2A+Kmi0eI/z9KocfAydQ7axse38+lfEFCUqfztIG+J6IpkIZBo3vT2ZAsxKJ8Bqe02hEkiYFeEUxAL8/DhgB1Pz9QeYX3SO3aosqi6LIE81zCSy7ZO3gUiiTDGJ4A5AXIgwY+s5lFmkCDmc2/Hzs3eQDRRPdVatTUFBius60j4jpp/3Uhd0ABBApCT2/wsuN3d8RluZWu1xJ62pcb/+8wy1eOCeNSFV085Kq3OmRb/AV7iEJ3Q0d/1qrfB27H5Iyxl1XUljoTtGomPIwMB2Yx2jDO+rnldaWMeAHp25Ijr0y5GluBrV7Y=
    rootUser: AgCr+fRWb8hEvx5tkBu4qsu7fo3gwOm2skzfVV7oV4CjBV3CIg7KBHn5IMOSur+dCtbsIw4RC/Cm810GgprY3wFhz8GmYw1KU63vSmqHFTMRuiw/aTx3kxed5oxum0NVnkMPYTE1gODMbCJaiHmO4wm6ZuwjyEg+X9aEi/znKcC0kjUEgsuxREP9GrRXFuM8vd/ZRjW3umuIHxja9PQ0SUE6tk8eoJ+1T9iNDrhnIzEvIICT+O1ikbQz6i/R4L/UkUu7n0fIsud0FM4viVetAv8EXMuJ2WwxGU/e1RQ2laGyEEIjPFUboAzET65CiaJNT9q7kRh6PxywSuGeSRxS/jyIkIs9SqEzTPCgJhL5X2zkXu59PZqaQHMrrsxKYEtULPVWxVYFMQmjAfO7b3JGg+V2jhNvyuzJj2BVsfyUqprVeQjrJTAbRB0Dv5tPPVtJJpDfV2nxxsWGUtG9LL76vsQIIN14RNQBazA+r6IA4iMGK4SBuvAPGIn6uF4WBpKnYmoYhchPTcgHc5RJlfQ2jpP8UpWBaHB8iL+8VuQLPsc8ilHqe71m7GLk8K38BI4u3rYGnKIp6LSar/lIzwq5z/j6JUSZ/MzsvrUuBHFBIdVvi1s9CDZuNu99EPvvZilVljVEbXZV+zUcbi0e4DXN+0Fj7q9R4fAXFELshDWHank5i6pj4dEel+zYZum7LQs4h2alAOTP5g==
  template:
    metadata:
      name: minio-credentials
      namespace: mi-carpeta-medica-api
    type: Opaque
