---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup-credentials
  namespace: multica
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAKiSNSqQlbnA22SdVufKvmpJt0wz8hicD/wk5w6DZKNd0izWzIu+4w2kK1EiDDmTmXL0Q9DuBHYjlyzoiWXAKbKzwq8I4p//+WWgk41hASCTuVjBYC6qcB2Y39uLpqG/3sOUqUV2ux1ufz215CTNLgW7Gtzuruzjo6KmsOSDsNyFI7R/Ee3tr1ETU/IIbClVH1YFeWEAiJGRQsKOwVHtInmFmxCUP/q2e0SPSy0uaYl3KeuhYKQo1DzFNhe8CLgMXKkQWqk+rkomCTrjMoNCYdsEfGJXKHN0YfNGHckGkJiBaBACT7IDtpz5BV1k6ieVnfQk/kf2Igq5172VEZJMmqWuT3kdJQUNmtI95KGLXgfNDGZd11H87NpWj3q4rj+op/JfH0UbozobBewDmlG8ivsgZ6XeZ73ubEgHo+/3kgiaNJQ09lABJfXeTZcJcIipJUac8aZQCjsugsaIDR1SnfklavxYIDeA22uggt67lb8AbDr8qkoNxasqngjaqydwgX+8MiV2ugETS8jmBdH5RHC24Palx60OH29hFi0yZE8dxZMmF6Hpsvfr7GFXPE/vnYZNeaAy410CqbW7zQOv0Vdv+W7ATqo+zJfjX+M0mGX4oSrloRV6UKJBMPwo9TJmcWqPIhQ4wFYQHTq8pNkrKIOd1mA/f/Rss/+31eoPO/h5XZLwNzagQJWZRZ0uCMex4nuyfs2w==
    ACCESS_SECRET_KEY: AgBZYG3uUiP2RUV6P3HLzcGI3lpIMse6qjaFllcu6MFCr3UhfjuQA+qmoSuQkI10PTcReani8HS/MmaZPkXOHZoC+1TyEakrstI5JbBLHVUvmnegDoGEW8kB4X7cp8qolYCZO7HgYpkSNDJP7Y5irUYy6A1m+IqW0yhEmJnsS8rbGoLKpQHj2GbIpaefRq1NEaZ5IHDT3n70ZsufWLYL7uqFWArFLDDTT0/NI3RVmrVabzCaSdydEBumJvbqYJuaSf0tuf+l0bPnO/ZQiX/vXAxJMJN1bq6njKaFKZyeNZYiPz396ICcUUkETQDzV8iBMpMZpg00vgoteiE0VPAKYlF0SPRT1ZhqyesO5XZJCdAUZ0LrWxPlQMstU2yQZ26uNMLhBrj433tmR3JZ6Bb+ez/p20NWZIQzfi7jnHp3a9HLKQW4aCIxqlgYH9GEOnIcI74loLeKbioSiMR2hYKQpdXJWGF8oAKLLDmP7nD+KkEVszdJ5Px7ydsxSlkx21iZt9P+oHjzxgH0CO9zxK/Z6HXhG8FF9E/uP2VbdW/E3yUhsNnPZ/JYfpK/in/9T9x8o2bsk3ODaZiVM4QR44+ovwsIPpez+gBejIufK8YXMHs2VYnhhjzYeTWSatwzM80BjwA1l++F0lXnvAWpMs+gjVvSgKYJtldWh2Zhd7i+DSraWmvFlyemzFDuiRqMRrDyoNoN6XFePvPANN+n9Qt7yYd+rdjqrM6Dbd2T9pcFK065zlAm07TbqxjuU5eEUNu3/38=
  template:
    metadata:
      name: minio-backup-credentials
      namespace: multica
    type: Opaque
