---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: resumelo-ui-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAaYvNs9Y3pnrWsZaeJTsNzz5RTFWlulqUyryTc4D2Gt7tMahVNy1qxLXZAc95+ot0UjUc5twFwVEze7PqKtrhf3v3Vof6aneVrwkpC4TYxXyH/+Q92/gK1Mw9Os7aPvPU9hV3Fsc4rIAYPwf5EtK5dmUDPPs3CaPswICDd0N/00EsdSjDpYp2RP3rbPONYBYm3RqHbWsJ9tdE+oCnr1kF2IsSGEIhCc5SY3zoVzzDO0wkyOb3mm8N8+0wulxaVEIC3z5kvy7uJ7w/wAJFuYBbgxGl4kkxz6EqsAyuwpEqQXN3gywzhJDgRQMmlFuDCowK7sjkcDczTMUM0FBOrAEjWkqzdDJPlTf80eyUaBxwpmn+kQslA/IkdWVuXOS51WQNd0u07xHhshvR6TvoI/jxrNkXVBU+rEsNEzHdSt8Zw/I0MAbGo+J0+Cxyk37Lw/PMhLF03omkKTHCBSfyvPzOgFEyGQqiSOVHgvunYQPpSoyOJyxqo138Ez09sdO7DiNeYozpKtvs6/faiKU0PDxzcW6y5md+1ajkF2KoXxfNIuEkqw2zWNUUfM+1/2iuQxxA/VG9B2f/julufXslw7voOJb9cHYOUnwzwSZtDrPMKd2kyDFiXjZcXk/OmoY5nlfK0OH242Mcy+FnnG21BV49rr2vpkWOfTDwlgoV7k9Topn1q/dORvmzUQAqwggxUWnNBAndOU5jBPLdWDzlZDSfXvjWyQqztRQ==
  template:
    metadata:
      name: registry-secret
      namespace: resumelo-ui-dev
    type: kubernetes.io/dockerconfigjson
