---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supabase-secrets
  namespace: resumelo-ui-dev
spec:
  encryptedData:
    NEXT_PUBLIC_SUPABASE_ANON_KEY: AgAl45Cf/GfojerS7SX7M/5BgVr9bY6sEN5cd9wFde8IlzhIeNZH9reFjVR0EBiIEvGuk2j9eRC5MXNBXPH1QBKN0VoIvLMWQcNJb/OlWHj33kR0s3WK3N+phxCeMqoTBlfCvun3Lc3y7UjHUW7mtIw4kx6XlhE5Afsi/2SQ78Upfb9tIg/4awq9BrdTNJC3HPu7kfUzMHDXCxer1JuCgS8qO2ns+U7lmoqB4/JH+GzWlJjpDPBEiTNTydKjrVU/aE+I5iDCxU+Lh/PgKjlXukTksJ7nUPsHJYuj1twBvML96a9DKlHH5jIiEHDH6tk8gFCzNy10iTeKg5C4z3dcAjTh/azIqZmS7RQvOHvnQ32sZFe+34FuPlbB1gvw8J393jKtClqS0JZW2Rllrx396yJIIzUtMrFB/UTHTxKZuOZlBMriqPylzSiW1T/4GYe1RyEdaVunONjA8EcOS8Uuol4SEB5W5GD5e/KYvBIeO4Cof+ij2liy9l1HyPZIG14X34YSs5DA8sxy8UluL5Ikqh2x2HBgjyKw8xelMUX4gABYYBhGei4gMSx2egVh4j/SD1c2nQ+wB1sitYH8m0JjFP/cf5LMqqz5qNMYFb/k8/ByjlGC4OPyitXyYX58x0m6PLehpT1jUnBJup0pDy+mhwhU25DWy53BrcK6FMjoY0GDY4zKgzL33PZYH04ZcjFo1loXbcW1G/g6oysK5u2j6SVmPz7vfDG9Vw==
    NEXT_PUBLIC_SUPABASE_URL: AgDb8yAHbv7+5NCc9lxRIXl3XRRTblZRm/qK+6jxh4WGE3IN+faYVtoV/VflN/tu+jLyiqYYgsImr7TEHaNwBdPDEcQAxr3NSr7ROrZ+F5ZL0U1G60ZwL8pZ5KkJX0jhelc3cx1ykKzq8pc+eU1D+C456VIZrUISNz53iF5hoEq+apKtUypDsyTBwAAGR1dsT/CotC9F6D3Ys883782BhDjW/S37ShBN7w1ttQ1wnw6i3lvi5kvVx9H3tigK1bGzqtQxPxM30R86VOiVFj8AY6rNrmQneTC/hZDcgbdpXtSOAmHqrsfjiqzfwyQaZFYVts2Rk7GZNCS/rwIakGY+6+ugTfvGiXOdpLqrCfii/tm7A1z6t90ChN1nhN1fwwZJhWYMdxVQ+oCth34lksWxiXZsChpKfdtN6AD5WQJpZeSNhUlA6FENhPLM6v7OagD9MQKsLQhe8XNu6TEOJDAeuWRgpFRoTCyBzBoRb8Ho6AwZIFnbxjpd5hG4DHHRWQymh7nbSq2ebovpCcVEW41JcFMPEzYBWPVbndjsm4wNVrc2M25Y4U84y6dnOEm+XSckoWc+C7nBMF3r37VVbLTrND7mtVa3oyL/d5zqpxVGdx71ZD6l2z7zzc35UTDJ9OX187sruqXarSfQYldiEdAHlw/wLhyYlrYtgsP+Ro/XEU5raOTXwybYbtKG4tpV7ZXElNi0Gw7gqTHlmfwBk7vrfGmsZ1fEUcMhIA==
  template:
    metadata:
      labels:
        app: resumelo-ui
      name: supabase-secrets
      namespace: resumelo-ui-dev
    type: Opaque
