---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: luloai-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: yesid.leonardo.lopez@hotmail.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - selector:
          dnsZones:
            - "luloai.com"
        dns01:
          webhook:
            groupName: luloai.com
            solverName: porkbun
            config:
              apiKeySecretRef:
                name: porkbun-credentials
                key: PORKBUN_API_KEY
              secretKeySecretRef:
                name: porkbun-credentials
                key: PORKBUN_API_SECRET 
