apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: __CLIENT__
  namespace: lulo-demo-landings
spec:
  image: registry.yesidlopez.de/__CLIENT__
  interval: 1m
  secretRef:
    name: registry-secret
