---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openai-secrets
  namespace: resumelo
spec:
  encryptedData:
    OPENAI_API_KEY: AgBoep5Ge/IRTkK3ppqb1qcyqiePwdPwXVwZr/FXrS47yJtQp3B0wjxNrifyKUHv8jEZaFqLhfSXNSoc+eNbfKxo6uft34P6vFl6BM7EJ34RXQwVJpbe/+Xj4h8Gs9XnJI24F4iTlPBVqj/IVN1+aUEhVaxiDrhSumgNcvewXV04hbBrBMGLimBV6E2qd5Lk8y+S3w/pvyDEJ4M6zXj15eSJ+STKFc13MUNIX3Uz9y6l2uf7ff0I53zYlPQJwNLPSW4gPQcWJVu88d5GH/9+XLjlcdD8BG10h1slnJicDs4BKmMDe7SOW5ji5WUhe5IKfuRq+2SLZOlSFhEdKlPGIbhp1VmXbVX46U1GUFihdKcOl0jXHmeor9chBlh/CfcWi57M8lCiI2FeeQGg5A/2PM3SjT64IgKltXXu8bMdUpZlO5zRokoK8x005NGYVubmfHWkYuPIpmv13h4DKlVZ7jGzKa9g/s5Q+jqRtUA9zPMH9CAKFz9/sw6ZKW4blacjs+oaiQGookEBotUUpTh2cu+0SdP8NHrmHt6c9pN+jLme8QdIbrH4h6BAmF1d6u4IM6UL6GEpoVSVkE1Mad3YC/QQu4doMkPuK5BvbjZJi/PdOjXREr12sPP/gocgK8dPmm5wTkOvwspjFytouuEBBGDSnf1wdBvdQY53bAx0yW8EzhY+yuv0KKvpxdO6Q7wm+KcYB74MTosHtLjnRCGMiy6B5BZ8gzPmAGD7aWvm/HVcuz1d8DfRPcjaSPYebG5doIOCz0N3LyHsik2QKURia3mj83RYZVycWAtRAbY06fOQs4puBvj/JC6cZBzMkiDQPrVzg2zCNODkboPbdKe9XF9U/J7mShNMRbyaU7JjWY1E9RmpvrI=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: resumelo
      name: openai-secrets
      namespace: resumelo
    type: Opaque
