apiVersion: v1
kind: Service
metadata:
  name: resumelo
  namespace: resumelo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: resumelo
