apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: mariana-toro
  namespace: lulo-demo-landings
spec:
  image: registry.yesidlopez.de/mariana-toro
  interval: 1m
  secretRef:
    name: registry-secret
