---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgAmW9r1wgPgKrsTzcc9mTIcipyD1PMrnuqk1qmy/nR+MUiY3Mk2x6dHpU4DMYo63M8m63jGHcB2PwSWvLbWD5DZU5CCfnm+rweqMW4Pn19SuylgXo0MEy0JWmNYRak2jVwFEBPHPlDZYFZO8PG+nnTKqKavHZHsHdYQGE8dA7SmhUQoyngsjyujrC+hv/heAi8vPEvNnbbAi8xbgLhxQwg0mLvhF436v5khnaxjbNTA7XQLykNLme+PXy4p58ZRPG1oncptUnhKugjAZ8mNYvcCmI8LW9M6DB//dzxE7KgMBYFvCHSGN5MAQ++vgge0TTCGRhePlpi4Zc0Suih200maU6jHDw075sBs4diQMlk4Sc+KeXkGLmVI3hKcCPS+1AOebzfM7P76K50W3ipnMWTbG8/43VzdnVl9msjws0o7Kk/SZaFjLwH6UWlZx7+DyllM7C3t8riy0a7khKpWc8xFReWg3R/3qRqlV0y/LppilTjzx+ECdgOVpj2Ldh6afS+79li8s6M5Sj8HhAA5JcMFxQ7JLLAopd2a7EGfVXz4FQstB+5BqjKxNuyOccjXVDTLX3bTQT91YXk8RgSdgXa3u0T7sdu9WhXAd2+rnAU0dLYrn1iiItdUViSxl7fxDnrJeOoBWEHUHtNIOA1RAQsh2JSVf7daFQQoXh7PzWYVajIGZzXEIoJBGie6UXMf6WYhjZOxep9kSCJZ2yhuxq9y8k5Kmre7zrCrDGx4MFZiIAVUTZpx78ZCPuK/O6kMHqE=
    rootUser: AgCGgYvnQV3MDpXGpxzDtcEMDE8z2tPNWfIlzCd3LNVh5xzDoxQQpXjLbKviepk9WPM/xS0K4xWn05ykO2RxiX6WsVcPFfTcMKH3i01sp+kLlA5Szhmkvx+qI6zElqGy/e4Rs3EmDASx40iqO6MJT7zesEZEltuTbJlL1EmGVi3xBAOugAzY05QRbhOAMmJJ5K3ertBokHtzSeLa4fqNTaFE7t0bCyMPY6rLhMixQenZgXyHPSbC7gGQHZ90Z7nlrM0vqWxceEglhhIytFJlqDG5NODFmn5E+0sFo7LWFjvw3V7pfu/17QUtcparbrJ/78QHfXV1pwnH9EdCBD+1WWA7hYoOjidcJpGoM6nHT0i8GkCu15POvMcW0lN4Pp2QwsEevC5Y5RRgPiHOwOUxIw0O+xCVgoKNzCHqq4GCL83O0CeqSx4NV3bkDyVdRQ6r1ojpU7zs7iiQdSVRqoGVh4pfPF1SdyBIve8Q8oUrhEG0642cxuBoHVq4fL0rhVNxJ5O0mHnnserdZEEjoTcInDjAIHv9XxHDvykqnnyaE1VWpcAh+UpJLzMdp12ptAb6Ht7d/rHIcmFQr74q7vs97N+Cx31S47V/LS444o2mx3dyesEbMGm7NHGM0fnMwIkf4HDYozInBYYOABsTbVLIvnX2lvqXbCs9n2HP9M5Kk7xWMnN1XatXvH4tZQfnlYQ0cSkuazTR2g==
  template:
    metadata:
      name: minio-credentials
      namespace: minio
