---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenny-psiquiatra-basic-auth
  namespace: lulo-demo-landings
spec:
  encryptedData:
    auth: AgCnRd8x++IlNZQnW44IahM9zGrpLc2s3l2NnH6NnPhHoQRmEBiLC1gvIPb8+YOAJ9QzxJEpDv5uBVD1oL/MIYIp2p6dqhv5E+fSMrFPIIj25stz3Oi+tbrdMkRkT5RM2ofbZVw4gvz9u/Rw64v6C5BjABa2Dz9eBx27MK37dDja4stJkti9G86+9wjhRQcGOOsRG/4IqZr4/3LnA3e2FuCFIc9M5OqfnWjYKUYOB1SmHqlVgyc7kvVzmcKktnY+ajlX57jmYF0xpNrGjZs6fgnrBcF7Flf0GsYCl8BcdvkE4vMyX86p9rGKXce7HXfyEis2ufyegW5itmnd2AQ+K7XsHTfJsHORjQbO2L+KY14GTs7WmojC2lMfmBMFp3KtspufJ1FYIqispCaYZHF8ZRQpy04zVhXlchpHFUZX0d1KHaFwmSAq6/+iDkayFW2W8bGrLIA8sbSeBGMYmZtH9gylLkb40IWmkj4/nx24weDe5d9bg6u+LZUbS9uzhH+kYph8rcdnNaMDeVw5hETAaD4LmVKyxg43e8YJXGRuKV55lsiDL0YbO+mqmWfb+0oiYC/210zMSdEantVRoAMgYNBgcnbilQO29KCn+Vx0goEIBGfzl9v3vx0XWk+5dliiJTNPEzKUq7Rc0U0y0noVuCrcO6oHrPf2PQVM++axx7L5jf+ktRMmdeDeolqn9kjTavaAkjDmeQ40JoQp2tGq/yIIzRNp3XqBUFUSX5Nab8tCcNjB1LrRp+NNOBESjy0xYEka4lxZ08X5ofcqut0Wqf0HqaIY
  template:
    metadata:
      name: jenny-psiquiatra-basic-auth
      namespace: lulo-demo-landings
    type: Opaque
