---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: lulo-demo-landings
spec:
  encryptedData:
    .dockerconfigjson: AgBhPQwSrhQJXsYXHSSOXnjbNDRpb3l00ILx4OzvNM2eKCdkku0aFy3jSrisECmLb9vOcTuovejCzPas6rMjAwDJDa9pXduQmFNO7W1/amqR5YSqRwoX0nxq4CbvFb+WUITRtykVwsgUVSV1+5xc72bSBMNLZV86GfvUA7Zt05YFhG7wrrwlUnXCD1dNZ3l2JcB/EP8FNgQ5VlJNGJqmBR11WO6wad78SDeAkg8WIZt2RnOkyee/Oa0UAtAon0rh1EBJasD+EVRqWf88YzKLondaatfcVo8bzBaG3aGRq8S6KRwOciwBwhmhzbrJtfviEnJw4GnfUJfvuzQqjjlNsJoIjZXPeSkSxr1jvDPmyXMshm7Ylg6TKThWNJu5MT39JXCwS+GPmC/23C/IU/EbLYDD8k+xWJYm0bQbBKBsn87rpXn6IepKYuqul20kkd6D/P4MPF/aWSDdhG7rGjsUPmKsVKBBhEaMGEgsesWciq/bUF9EgU11nqoNIuhNIzowxKXxdlQUqLsditKVSAjkjZpBCYWtfzQDndVxXkY+Km1hywjzHENGYi/To6pBfTC42EgSno+0hC7HOlYdHMVHvJQ0Iy9MrVXtoc9XVM/ZLO/p0QVPI2nC99Iewby1ni4akPl7Xh3Mneh1y5UZwJ8lEay8lMrUwjw5QPixF+MJRniFs5kSEPg6kq4RimUjaYlO80Qi9jtX+ibtNOyPRSaBiTEDPE/fKYW+J7NKTwM56dJHNJ4TJ4G7DTxBHyQvJeXCrrhAjWqKFDwcoaxcYyO1DtZRnTh4Pb1qZoLnJToxKAQcwxzqjdaWIyEigyNc1Plt8kc605POdR4j5zW8V5+0L6p8mbRL22D7nTsJXOnS8xHsNRvUchNiw9oYxioJv72L3JBIlG/4DFpFGQNQZ5C7rftceZ5C2UWkmSHPgn1NvXgVgGyL0RiWZ1UwCfa7004OsVXMNAwhC+sV7I6YFtPSLGFo2/DSpVnkziA+/o7wDdIVL2Fy
  template:
    metadata:
      name: registry-secret
      namespace: lulo-demo-landings
    type: kubernetes.io/dockerconfigjson
