apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: lulo-cms
  namespace: lulo
spec:
  imageRepositoryRef:
    name: lulo-cms
  policy:
    semver:
      range: ">=1.0.1"
  filterTags:
    pattern: '^cms-v(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$version'
