apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- docker-registry
- ddns-updater
- test-app
- resumelo
- gotenberg
- umami
- langfuse
# - ml-portfolio # Deployed in Vercel
- tayrona
