apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- docker-registry
- ddns-updater
- resumelo/dev
- resumelo/prod
- gotenberg
- umami
# - tayrona
# - macondo
- lulo-cms
- ebay-kleinanzeigen-api
- multica
- public-status-api
- n8n
- client-sites
