---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenny-florez-basic-auth
  namespace: lulo-demo-landings
spec:
  encryptedData:
    auth: AgBgaUOXZzHRNWAP5TptvZJ4HbQZZHDNLG8NFEtge166IaKdzEd5fP7pA2RMifQyg0NK5FyxxXuU8vyIYxD9DX+OkfOhY68gEJc00OVV0MB3sdfKL7QI18gjmgGODxKeIoNic/wIReYBAkJ1oJ38iMJy+eZX2kmWeMmYfnvQOJm/eDbHAzPj3H5JpumYtfgDWdhKMqXfc9zkv4qynXqxVgCOZxmMrsytIGlw9smSOsG4HfdIrmO7lJAX5n9l4edD4q5OJbaj9EHLgvjr5GhuxaFjcnkRXUZpxM5cylBGSkMBmF3fAsT54PlfbAh9xxYxHivjd0B+370cavhZWjPZjmktz3ncVQWNYpaumC4N6Q+ns8loUEUSxgKgxIQFouLtv4O3zY/X0QRCSOZLkZE6cvus9eByTiEkMufMrQGl0+Ntq8QKM9kAbBEeeMrUBXVCcoP6R4EFhpOpMTqm8JOq4hJ2g9h2yOrJ53YoGMZGcssofoIeYASK5rFT9ir/QVSVgqbHIvXxmxGCHDfGrKRSrjm+2h012dPPTNPSpvOVoFJt00FWPpbLJNfC9IOgCEdQel4eAtxrPe+DRL7pJB5wERRhRn4fxUDmWLoXwo4gwt1KsbWxE9saSITZq1FFnNQLFgijEg84iAbs40i1WaB0dZ/ZOg+13xRZN0p5Ym0NIraj+AapOBLhWshm8JqiHl/+klbySOvYBi/ZjxTfilNVMoqlXKUX5QtQeKwBACtUJDQCeAIQe/MNmvjzhEaagexyjmrf30xYJbokDEPep/cOUTW7EwRc
  template:
    metadata:
      name: jenny-florez-basic-auth
      namespace: lulo-demo-landings
    type: Opaque
