---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: mi-carpeta-medica-ui
spec:
  encryptedData:
    .dockerconfigjson: AgAfr4GvC7qgmOssDAcin/pH/Eht1fu4kIfSXFAuBWHr94rdy4nFq8AKF4O27zyrEBzeR4Aod6exR5sVDXINaylVNeolUCS1M5khbI/xVUQvCUxgGm+Eqcye/YiGVGQ8oDIyIuGJjD2MJNDR/PZXAtDWuCXCT2ZIJg9sBkaqxyWW/xKo60pJUrDV5G0G32X0efLl42j2wj3WvmHpNYzX98NB1Y+BMFURR7C/RpZ0SJupIUDAFooUSIICKOKhoaifgyNgXXRes3q/HBTyj0HfjlbAQMyCa9Q8EsAt6VFMxsBhzrVrrcKlB/D0+uTI+ITvyyLKzsx50MzlnVqfBXxVbzFKPaUVRYqL2MtIrw8/DHluDK/PoNUvjLgqSs2NQDSNxPKJLr7cx3gNmUmH/vd0Vf1QtcUMCgBYLWJm93vYp24FvALGeLdyNz+LV47JKcVYn/PTW6JYgLplYPDMFoGpXPCke+8uU6yfeQKA8rW0qMVEYxRIX9YJrfyzUacdBeoHOjm7p36WNGBa1+7yw27t7LvC5rAw47D+gma6qn2w4KGtbjwnm4TZSnjaiDsbBK8i2cd+wmKL23sBcZdMpGqBO6VKmcovI4DW2UXzniHbX0DFTwWOLlMu8u9D9D/VzMHfz4aL/4hx7BAmM8bR8gDGJz2wA25KY1kgFbyPhVtRr/QWoQByePzTkH239cDm4jsmQclFGB1MQHpJNkpJJGuZLMtx1x+ICiDZQoPqjO8LsxcPt7XeP5Qy3kpKmOm9GRgnjVjZJYOwT9mvaYEZwtNpGMCcVLK+GOsSJq1BPoFtukl4wUnSfvvJi0QJQC7s85+SHbspD3H3itQZaYHoG+lZEcWyw5cFnfDBfoKGFNRiMCPBCOFHV3kPIVgFOKQ1jpnCOtK0ZB4NV4is0EP7YZ46w0SbzSeVimSRt2Tly8S3muv+ahhHzwAFuk6bRzEwjecT53CbpQtFd7iVtwmZe1pjXscKEW160f3eIWSkIDFtu4wHfkWp
  template:
    metadata:
      name: registry-secret
      namespace: mi-carpeta-medica-ui
    type: kubernetes.io/dockerconfigjson
