---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup-credentials
  namespace: n8n
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBieIV79RDkUykeF9uTetkrS9w/DQgjeQY3X9A05ViARtK28KbRnA5MvZWhf8680jWjxD2vRKxrO+Dm75S/phqJ5iGMvgh2KT1nTAwljXLVIj3E6hJ+WVRYCYjCtcQ8HYG515tJHyU5/0HEnIKRkBRhco0SgZemA1kE5cyU4U550oDhba6bg8u33w+cKkOYuzHE+IjVuQ2Wyc2yNx4bjscQg8EgTKacYUHtzSIT2sxXeBSJYWmm6tuXo3OCcUAm5oSv4WcQvkUynhTWRuGKCvJltAshMDP6dzTpXBK1tDeRvvrB3R4CaqFejlaF2WkW3stnoNYPAPMADNfh4HBr0uQ+jgUZcE/A8VL7DZgfBzYyLM7VX+yV/VeVpk4/Oxc0UEVpOVHk42BR4axExhnyCPnqgN4yaHCt5OkzHzn+V5r/hjIr4mA+dBgm8ACc1zV0d0HkYEHxqLLMCGcTyvS0EouKaWjsld5y+UQyXvMYDrfTo3lFX+wZ+5SpjqcoatgQSXMPD0rjZNn09scu7uNmCSYWK4tMvRQFtx9Y31Arhov7mpVxiWjOW1n2oro8ZcCnzKZ2BfzO0V2mLnVzIcAi92im090CZyld1iXxEW4ExCXmfnKQKtSTpGsuq5Vyz1WWI856bFRZoQ6kAKnh9RrCby37jNmT+94m1yKKdNaAIrk7FIUDX6hEAULT+MH+s0frlXbDZ6CY8Q==
    ACCESS_SECRET_KEY: AgAiCA41a/2y8QR6y5IHwLM9Xto+42qZ3StzxusTfiHGJCDw54BD5QkQoZY2tp/y/n+VaoaK0Xg8U3ycrzUbkYucvpEjT3mXJLEwaiRWFpgJwyhfmk579yDbPEy5hCzuRvp6DXdzE8r+kjNl+k8qd7MsaEqczA7q6dzYrSEKIFfna5voTgiugyK9gR/hsUfNBUoriHW+TEpha/Qh4jvYpBT2eCrohlWOPY+QQdL6xuWjCrXKP2AllBtKA475ctUiGLYh0oCf1PJWn9GlX9VbMdzisLAyhzZaVLuZMtHDMbeecNSxVVE7a0OOkcj1wlm+lCa/7Wi/jpAaUkg+s0tvCXMpQhoP1+qvk15fr258NRNZuBSs5/mEbL15kuYAXM/OJR8RE9Jit4vDKF2ykV86e4F1P4ZhKI6ilUnN57nwzacJtovWA7X/rGGECBYjWGxzzWruniVZFmyUN+5LUk28CQn+EcY+TUPR3KSY8z11tr72AtOmE3+3V+FUeJ5pbjRY4Gos0SldI9NK9eJE5NU1vEjjh1WtRVoU4AC3t61cc4CS9Q0YhOylD6PBY43cUGygk0+/OTzaZq+/2hQ/TVwmYmt/UCGNgClBj4o4yf3zArUHQj5+gHA0H+G3fHy5iQ0QW33ZOHc5Qn6zSySgOsfAw3h44ePdKxPmfpnVlKBViD3IGvxsnWYxQeqaJFBpHj6tcdJi59v5+jdzV9BgDuJ0DaFT9JAsfFLF3w6INI6TbgZqc//X4CFIMXBX7lz+H/dCuUc=
  template:
    metadata:
      name: minio-backup-credentials
      namespace: n8n
