---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-app-secrets
  namespace: n8n
spec:
  encryptedData:
    encryptionKey: AgBT3x7/iKVJvuqpr6CxG3avV9lhoYNDGhtkNoHQEaesJyYA6AyaH4abfxFijCrhD7uLQ/VeKPydVoIenAN5GEtBnZztZ7bDBuTRdBcRfbLbwMykEc7e/Dv5yZb0BJTXhSg3buIcz2fgZr12+ctiXN5PTEY4Jz9ONWeFWZrE0XGW6Nc6thGJQsYm8FJgvWUVDtv2TQEcIY0cVBDJALZtPAxmGBLy1ta7rzmdqBk/Yat181GXOWwJfyJhmPtUOJ9hJKMIm9omdn3bHD08wUxyje1boRbroLy0cFfQvQweOiiOzaZkByvbaXZGOx5lPJMFPIybJb9TbWP5yCW7jx36MATDynMs14yAs9ZGxyUNKZqXwOq3BQWFw0aUI9y3QvvgmkTShf5yLkLy+LTR7nuK5I6dpXmc27EI3jGP9Ykq/461d9vg/bHZAnVCcxgmGLwKldoknPul128h1jmc+GfNW9OmEDKKXZAMGd43/fGLAsxcF1GiywDvXH9a5uPNIUMjckC4uyxwos+fv+8GUB1mLm1HHPMNVYqA3tuuEczjdPCrxwAEaJ6V7Ktm5Ro71blL/XcbsORYXJjIVV+sxH+0xXnbnGPbyCMbMN2PfSu2wNcVzG5mJ/kwj1dy/BRQaABLemWKS5DPglfKfHTMNRc5JRlCa/sJZVnkjn7kDWdoFNs4t2rpei28WE/b1AjqapTVZdrTRYd4mp08w3PiMH6pqOe42jpZRR91LOkDrsdYIchjptDm9LQU5sTQgUMOKLuZmUChIjPTOOZDbywtz1TYxiQo
  template:
    metadata:
      name: n8n-app-secrets
      namespace: n8n
