---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: medidocs-ui
spec:
  encryptedData:
    .dockerconfigjson: AgAhhkWFGaKyRGX8XZRWvdNV4ohpM0VA7nWykaJhwXuNRPBqhoZkjH6Q5dimlFoDhP5lDABqAa0egpedwRzNVa19ltgdqrhWlZgo/jwvC9jg52Bhm63Fh9THwHQXjyBboi9XWv3Z1SzRSQxj8TToZKOmaGdWtLt91iMf7TlLT31abdgwT1dd06ub/CnL3CItIHVJ761UitnhLg7OeCkVJ52BIve2Yck9r0X8o3GGH5myMwnMdOv0LANCe1DNoAEP2LR1NX0nHSXx53ivuKz0Byz+eYIN3cXQA8n9xAq0V4l0fOasTVQ8xUNjFB7wi3VVvjxR+JUfkXFz783WqdNNKdUmUM/ni8e9/8vm7aZ0eyPwzXHZ76qjGf55vXKxJzoYRFesmC953wDZpSrjPlmvfn+vP9FyCfe/C5kK2SzUioNKVZg1IIWIt05jtG4Xvb9BAHO8oPKK1FziF4TEccQzv06BVdXsFPWkH5vyscEXe54ZM/NDiAQLbxWwDJyDgSGbnLJu5m1EvOkYKRAs9VG7UPh+gaSJaJHEHKy90gy+arxE6MvYeSvgSaS2YYLkrBQTgEDncWl7mOzPTuNpie2B2VWmFoeWB3z/efs13RQ54WF1pRs2RLaAE8WOclMw7EwS5JLiLiQbN1HXQUQ4l1GNSMtcd7+6LtuTmLJopc2m218gmb+RpEYoptIJNB9GQop92sZ+0z3fEaN8NJp+jUixLCl4bZMYM8MRHZDM1xqbJAKI63XJO92z4AH1p1YyrTl14fbzW3WDzGdh04u/9taRVrj7Xi/TAWalp82MrZ0qr94tlZcbeaXH6NMNP9/qVuJrBQ4Nnml3sttkh0B/6qQq6JYx9O4uPB2a1mpLbolQGoK0AcnjQG4xJ1ECxjtde+8HF5AOokHp1xHFX/6TrqlLFTKx+82hGzXj8QXnIbuLc78Ba0dIi34hs48XZxDjpj6urS6Lbp3pccSH6j1d7alD0j0C5jszKJ2Y/BcyeM8rYLg2pLmi
  template:
    metadata:
      name: registry-secret
      namespace: medidocs-ui
    type: kubernetes.io/dockerconfigjson
