apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: katerin-osorio
  namespace: lulo-demo-landings
spec:
  image: registry.yesidlopez.de/katerin-osorio
  interval: 1m
  secretRef:
    name: registry-secret
