---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup-credentials
  namespace: mi-carpeta-medica-api
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBichqdJi5TtXM59JpeVxjw7T1jE7GUxLHATXC1Y/wkDcrN+gWEfDyNfvn1uD17jk3DkoqxwAUUaKJZAQB1pBd2GQDC+CPkL96uy9pXTbEFRV7+/y62rKRHGaSNELMBZQwfYSXCkys5UZGLNkdB21i3IBt7a4sTWa6yhwo2ThBQpYNlQK4oyqqXdPuG3LdsqOWr0e7V4Pwiwc/p6sWHZe8JA/GV4IQvFhP2LdLAm8mB5G2bxL0NQcQhz7EtZGXLocWAlNhSTLMsj4GJH3ldrSZ5qs/Vw5eELSzr779Tadhiryeu+QYFh8cxu7qzPR/AM71grYbzpggVEyTA0/kZTmXzhN5FEJFl7SiMVZlIczWNW7ZFEvPFQvjqU7joLSjkYTFMRc/JZGa7nrS7olW3kfEHAM7iZwebIZh1Lf7YgblUXXuP8g7wCt/G5LdlefdaUdkulRWhE/yiNI8zaXDeXGWN6b0YsmA73d+7nQ5vdH0rxnh4XkGfLODig5FCM4SqVIW+PmfxROc2vOMIbv65fUmsCHeEN5cWvuJBqGh+W5yavayhEXVXmGpvbuj3zHdIbOt3gRyyHwXjH6LVIlmWd9/Rx0FgZ46VQR4vbm9ghotLjuYrUnZAWQi3fnQN0ZjxDspLXccLmOEPs7oRHhnjz34zPGooN3HK2w7w66xMwtQSTsNHDvmdG0mPNGNKYT3RmQ/OzvuamQ==
    ACCESS_SECRET_KEY: AgC2p7IYKSI4nvjRwaDacspoqm5ETrYeTtnZ19CaUoY1ooSt7ujiHriFv3e62l/9oF3+WpcLmiwJDIsYoYZLQ3BYE5DnSta6tFo9Rv+Pc6kfGCkQwL5jD4fCTtEP5pyeyFjh/laZWBJYXZVTUsiAVmzemOLdOUZbiPea92byRvVXClOSZUBuSC09deO6VP8dobgR+NJqMV/e6Rybr3jSgAYJLY979KcyFAtIQUIuETM//FZb9u8eHZlWxK3fIQZ1Inj5ZM7ARFdnlgZnEJmwwRToN8y1+BjToF0LhYfw8fLu61UYhJmr9ZhqtrjjQkQpKmstB4t+Yai3ZHUEhKGFBctIZ4cbLgGcsmgdReqbhVuuZ1ZdcLY3VCxxlKdc07xhPwa3KczZX35wtq2WFw4vlpDy1XuWkPk79jFpj8DZg2feDOxtcYyq+MvedeSfbU4FMLYEq/ApxQW0/Yy5467RmrSgyWkD5IwFOg2+p8TJ3Ncbt0meatSlz7bz0//b5ua/eIICuRNBmCuFa5fxby0vAg0BX/FA7xind+nXK4k5CLs0TFHgxN4lwFesUr1tFVGIVZkF8QEOLrYmjAy90uefrZ3d15MVo2IxjJPXiSh3RKP+iiF4VJCiNul3FqvMe5oRPj7mKnT/wQiuU+qYVDPhIJ7qfxuw40y256Oyv5raMkXf+vzSPKMKh1BW17MrQ0jlbdqVAUlvhknEbRHPZbW0ybA6o+VhlZbPLUqeU/MnqcM88IqP5ny3ETbZ70cg9NNvweE=
  template:
    metadata:
      name: minio-backup-credentials
      namespace: mi-carpeta-medica-api
    type: Opaque
