apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medidocs-api
  namespace: medidocs-api
  annotations:
    cert-manager.io/cluster-issuer: luloai-issuer
    external-dns.alpha.kubernetes.io/target: homelab.luloai.com
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [medidocs-api.luloai.com]
      secretName: medidocs-api-tls
  rules:
    - host: medidocs-api.luloai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: {name: medidocs-api, port: {number: 80}}
