apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-registry-secret.yaml
  - sealed-minio-credentials.yaml
  - sealed-minio-backup-credentials.yaml
  - sealed-app-secrets.yaml
  - image-automation/
