---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: medidocs-api
spec:
  encryptedData:
    rootPassword: AgCyyqcxOltadcSuxnw5w4FzhhTPVTif1Kb3JEvA0CnRr3nkhUjOxJ5IvsI4pSV1hCafaA2Z6RR9U0eIm3mVT5VAqCGd2nRvRFXCcc9mG1AS+N7WTddv/Du0iVFmmsZYU7rVcLnPZi5l6TYuwX2Oi96Lja357ls3SSTSHlaP3l+zhasA1L3DbeYR7oUBtHnMvgPojpn3JFB5nDh+0xbu6lsN0lmQTc1xcflDdpWFQBk7D3Q5/qfEObsvHvYx3Z5cbLhEc0y7X+uWEraCgxe15vFMe6RqqX8Wmao8rr4gqCR2PsVafvZqNrSBJE3/OF55QeF4dY0TERgSepdaUkTytPttG80V0N3vuCWygiXgNKa26tE4rqvEABTfZKpnA5dWFBY44vNOwO/JSipgJLtU+JAYOKqFTlZBYjS5jHe0hc7kv6noyyNu9HK97Q8cF74REuRbCyI2l8ofl/OLeYrRuzlOjhuitMLW/yTTvgulrb/I0j9/5a1rHcfP9qeoqJvrtEO+Uc/9eq8Wc2/+KxMSS+MiqyZhS1S0LyRSWg91ECuYJaAfWPsiUXPd7ng5QvwrUsbGVe0VdXY9hZKJEehxRMwztxzQo5G90EjD4+u0KZjaIEzf2nNy4FNcb1oXjIbonkCA3zxPwUaxnBBxIouU+Vc6efMtceByqtoxNFhax/WD5A2NnPjSjpiLc81eGOF0XqlUfoIiAQrmr8BGK1/ry3LZYBOaufyGRLYAmQ2KD+u5TllZkCnRGTsyKWfS6umYy5E=
    rootUser: AgCeFBMlyoOsishx87wNW01pTLohy7x6LD8cZaQx19Fehd30C6GPRMnPXSbdpFcB7iHUz5bAA5JDT8gzA6OX6LMxxfdx/yjg9oD3VUUVW5SklYeMmD0nUxVFjjAbbiIt0h6gVbggqxG8e7/wwRXqDKltEAfXIIJBZdnCtxMpeDOnfxxpOc4YRJupOR5XhGEd1U0Tg5QllPxl+XuqOHqxnF6GFWDHT+91DaVU1VbDF3nEy0jEcZ5Q/PE6ZDVN67AD5LZm4Sho+Gp5JeZLpE3Y0Z8zCZuWGk65rcyiDSyvnoAz1CiLe47gbPcRD/Im2LoIkuNq5+I1AxfH9cgiul2AzZi6ANSMnLncwcBA7+ydUahjY+xqXs+eEoy/64f94KYIBXJN+gF0OQm14zOTPQUCb15ncNtDYq3CTGHZq0rcGbeWGKIJct9pavnaCrGxiAdaZ99iY1gcNSfeK6hf95Q2cnidzHT2I5FiohqTOjHovLSrrygzFACBcAXUFrOZOeWK/RrPNMLYM0OXsxEnQv0hL6rzUqAnQqPcJYMrwu5eN0fNQORau7hOd8DH4l6Zg2ipmbYtyANwrlwBf2WcGv1jgvlD/j7JTiguSSdFQs1mcb70jbI8GZ+N9qtxLSUFi/IXQ3sKWurZQvQnzsnzxQBz+rGvBjAY6FZRs634fYnquR779i2K8R1E4st0CKInirUfv5Ztz7OsZw==
  template:
    metadata:
      name: minio-credentials
      namespace: medidocs-api
    type: Opaque
