---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-backup-credentials
  namespace: medidocs-api
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBcSPLAiHmAj3IywHdWPhnNlqHaJ/U5YiMw7jfML8r5rNRj8g4V7ftgvr6Xuiy2NE4FVYUVIqazbAPy66uF6+EMVF1GBhhfAxFAYIRK3W/hN2AnFJ6Jkob2RCTQ0YcOHEcjhixxA9cm3T2203HeF+gcUz3471Hmblf0Hv6zxl5yh70raj0dH68dZ2nLblPJq/q6cY6MQ/yPVSFy0xY+wPBH6CVCWk6Qg/3MnZFhMYzuYbbQ+XfaimKPKAFWy1MG3kmPA6Z4tnmB9aZWE3BWZn00mtx9YEieO3fBc4VOLcVgS1XjTGoHz1nTp+Qz403fTGLHKNpc5+XzPj152i185SNiZb1yJxoyFkGijgMNba4gWOJC+jL7ntBHeMUGJVW3rpmUsfYu92KqjgrUMc0aJJOFwHrI/xoN8iJa8h5n56ZdPmZ33pZhrKQhKuSCNYz0p0Y6hNXzwoiOh8b2rVYhv0d7VDX1hduAOXScKiCciIxzS6O2zFEsBtt7N5/rJi2NkVKhYlA+E3402cZkKHqZhlvdkC8wEmKO7HUIvhg88CM8XdI9+So+jrVC+Vh+B++/UpG/hDnILfHDvib/ZQAMR4xzCzIYl8WZgI7lt58VLjf8HKGnGgmapmoDoObDvRYjyyl5UwtGwVagBCkefiFcK9RLpHyZB5nVwrM7Zf2dXZW78B+RntF0OamjGTwHnCxOxdLDFd6TJg==
    ACCESS_SECRET_KEY: AgDXn17WdyAXlurrXRmQD79X/TdUdTqvnGUK3LvuIWdfJX7jGJF6PZTMVWHPDfV4dMqQPaVozr1KML8vyPRkNJUlVKnPVPXFkB9ewT9SRIaV/iQzKahRNsWZuijkWn2X//9kC+HyukV08oPBoZWQwtuoQrZFf7IoNXY2m+dwJZ3BkBn1b4GIZ1umHrL1YlaI6yCaPl5iTxbAcQeuOH5UotW8xOeqVAX/3rTUu++3DDcYyY1h0FN0G7qFscZpCiFi0g1ZW57WYZQvokeVXRslxcsB9laSPKvig2HuPaMn9isrUkLBi80TiiUxxSrVQ+2zvv+1gTWY8KydDEdZuCxBXomtu9XrMRqJAlKey0N8fwL05FJSqXNWz3Sp42+1QfAlqo3XL/VHSq86PpteK47ToptrPDSQtq5dnGiEY5maUcZOQ/wVYZo6SGxUU1ThLbDN57PhU6I/G6Q2zfXxv9wunyVxBw96QOaglRVpaJwzzB82Dwe5w2bG5C1EiLFv/ratdM1zkhbUPkWS4XYWgt3rUQJxv/YKSq6pNust152Bw+vmNs/ycaHvqtAxTq9NlH0UF6fNohnEJLl/2Ln9Zy4ikYIea5Tb5ocr4VYtCWTUHnZqpdMqRsuH8n2TSyp2IqdCjxL4r/sZE6vswp98W9MzJbPV5w0KBWtCg+0ikSCDm/Rp3md4TLoXhpZtVVoab/QMB2xgINbxxflw6oKQqEVuKO7Z+BuqgH2/CrOH/nJACmwhfrRq6dNZRRac6YEUAZrgdZo=
  template:
    metadata:
      name: minio-backup-credentials
      namespace: medidocs-api
    type: Opaque
