---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: medidocs-api
spec:
  encryptedData:
    .dockerconfigjson: AgCBfFdph2rtrhURngdYw58lHyhDnHAPVXNqdGvDtfaISrMqbIwypSn9tm0R8I66PMB0qssY9nlsgdGvw0XVihORE7jg5LvKN43L5wxMjItkkZBaL+q/WIMJjKeWRMRufuMMI1Nn1mH65zOVxBX/EEFTGja1h0AaY5VfneYmYXGPL+CQ36UjCVjWR09zCV/fSBiE+p3oKyXUrVI1XCaS1RSmXhnK43GbrcHtvKGHbY9hpifQWC+QV2EYcTCh5ztlXDQ/wenlWdtAAFlOuPFgAAZDxwGE1R1aWXsKKzWTgtM6ez0KjwjiV1VQOpOObONbTjbA0gFM+9/O/JXM6qA03BCJMUwl4JatCOWwiicCwBtx4vf8tWjdoIWWIxMq8CkCQ2zEZUTct7DBrgTd8Apt2MKET+J0dKcbVGvmpT2HRFMzQbJiVC2oarQKy7GzAmp+XUes5ulYeTFTahgW7QrtAJb7fYBLXqqAvVuvBneFAh0Ls3bctQX9Isi3k81rn9OoLhJP6/ER9iYwWLYJPA8Uso0IZX0eLK4PO0JqrNVSi+pDu6+yc/AuVH2l0qoiCX2qsScyimATxmO1xicFQl06ul3suUwWEZ2Fcy8g+51+5gbErcaQAkG7hwRne+wJteGUGow+IE7wYMxRb0J+HzVzwIamVGgr0tKUjvlmdN03YbWnFvr/6HOyUhJxKAlxaog8HPAQmhcGMx4B9BwJmCWsNTM8szHEMGciO2UmIBb/qft8Ezwlsg+TJ0cyWhg8XYUm+C4P9NwkhBGp9bu07vCIRVHh8lfzZHzSUsh2KFfKwAxnI2Y7uVjrZj5KcnVvTG10VqytE0BoNsFOGPrOxpmHcur8v7lmxxx/CHOWW0dxQa/uH2nTURPTmVZbqGRycVpGY6BlHWBHqz2muG6seFRErj8OGFZowJZXMeIQ8cp523m1km5eKXDWLwoR/5kQ2nxxfhD/RhAy6+30/r2BV+iPGIovK+dfbhms79yQrvOYBlGiNWxs
  template:
    metadata:
      name: registry-secret
      namespace: medidocs-api
    type: kubernetes.io/dockerconfigjson
