apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: resumelo-dev
  namespace: resumelo-dev
spec:
  imageRepositoryRef:
    name: resumelo
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: '^latest$' 
