apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: resumelo
  namespace: resumelo-dev
spec:
  image: registry.yesidlopez.de/resumelo
  interval: 1m
  secretRef:
    name: registry-secret 
