---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-helm-chart-value-overrides
  namespace: alloy
data:
  values.yaml: |
    alloy:
      configMap:
        content: |
          // Loki remote write
          loki.write "default" {
            endpoint {
              url = "http://loki-gateway.loki:80/loki/api/v1/push"
            }
          }
          
          // Prometheus remote write
          prometheus.remote_write "default" {
            endpoint {
              url = "http://kube-prometheus-stack-prometheus.prometheus:9090/api/v1/write"
            }
          }
          
          // Kubernetes logs collection - all namespaces with increased file limits
          discovery.kubernetes "pods" {
            role = "pod"
            namespaces {
              names = ["resumelo", "resumelo-dev", "langfuse", "umami", "macondo"]
            }
          }
          
          // Relabel to use pod name as service
          discovery.relabel "kubernetes_pods" {
            targets = discovery.kubernetes.pods.targets
            
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "service"
            }
            
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }
            
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }
          }
          
          loki.source.kubernetes "pods" {
            targets    = discovery.relabel.kubernetes_pods.output
            forward_to = [loki.process.filter_health_checks.receiver]
          }
          
          // Filter out health check logs
          loki.process "filter_health_checks" {
            forward_to = [loki.write.default.receiver]
            
            stage.drop {
              expression = `.*"GET /health[^/]*\s+HTTP.*|.*(/healthz|/ping|/status|HEAD /).*`
            }
            
            stage.drop {
              expression = `.*failed to create fsnotify watcher.*`
            }
          }
          
          // Discover Kubernetes services for metrics scraping
          discovery.kubernetes "services" {
            role = "service"
            namespaces {
              names = ["resumelo", "resumelo-dev", "langfuse", "umami", "macondo"]
            }
          }
          
          // Scrape metrics from services with prometheus.io annotations
          discovery.relabel "prometheus_services" {
            targets = discovery.kubernetes.services.targets
            
            rule {
              source_labels = ["__meta_kubernetes_service_annotation_prometheus_io_scrape"]
              action = "keep"
              regex = "true"
            }
            
            rule {
              source_labels = ["__meta_kubernetes_service_annotation_prometheus_io_path"]
              target_label = "__metrics_path__"
              regex = "(.+)"
            }
            
            rule {
              source_labels = ["__address__", "__meta_kubernetes_service_annotation_prometheus_io_port"]
              action = "replace"
              target_label = "__address__"
              regex = "([^:]+)(?::\\d+)?;(\\d+)"
              replacement = "$1:$2"
            }
          }
          
          prometheus.scrape "services" {
            targets = discovery.relabel.prometheus_services.output
            forward_to = [prometheus.remote_write.default.receiver]
          }
    
    controller:
      type: daemonset
      
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 128Mi
        cpu: 100m
        
    securityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001
      
    # Increase file descriptor limits
    extraEnv:
      - name: GOMEMLIMIT
        value: 400MiB
        
    # Set container limits  
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      
    # Pod-level security context
    podSecurityContext:
      fsGroup: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
      seccompProfile:
        type: RuntimeDefault
    
    # Init container to increase file descriptor limits
    initContainers:
      - name: increase-fd-ulimit
        image: busybox:1.36
        command:
          - sh
          - -c
          - |
            echo "Setting ulimit..."
            ulimit -n 65536
            echo "Current limits:"
            ulimit -n
        securityContext:
          privileged: true
          runAsUser: 0
      
    serviceAccount:
      create: true
