---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: mi-carpeta-medica-dev
spec:
  encryptedData:
    rootPassword: AgABNaAAhPVp/3bnZUvTiWi0jPAjdpElP+hIQ4olfpGBqw6Qj2vHQpRJz01Q1EJlYqoa+bn8vc3xr+vkZ71s2YdJSq59swnH+EZzmjsf9HstvdIZ0Fys3pc6ohyyrOJUmFr0mFxxRbfqCN/eGfUz4yxP8Z4e4JMN1jQQ5mCVRbbFfIN2drJrkt4nXnAT+yDVknOm0Wme4BxMrBjDXantsz3hTd74Kg+sbMcET2g5j8b6BxD7LWEaHcMV9QfyY1Q8f7Pw/YZ1nEi/RltQyhxzfmaYpJrczpduy8fA/BFW3rNySSiF8f/qG3wtVOaZKK1IH4aLe0gJ33p+rwBX/Zv8CoW6569IPH4VHq77SKIulbiJByb4EPW9tfZw4PKYBDXfN1mxyv1x1HI/SKfmQnILZH5JuTyMCsDIkuauZGGM+WlolDz//XUQgoezeHPaySJ/qzANSeyFKopLCxa9QE6ehfuzzBN4UKhxeskbyXnp+rM8jkLqnwCa8WASxRiQhnd9utmUv7SkZppDjaMbAmj6HKRXESea3K1Hz9dyNIyh+kqBe+SgSVGsRSwaZzIF3jw0d8+UbZIm0hnhnMwGLHhExpdPUdzpOLu8aNw24vqDXLQTwkHJYQrG9a+b05jSEsD7aXHuBmkNId40nW1bVJESeQqpADAsidQyz/xKacN0TVgpgTUAP226LiWM3cKiu3LBFfz9Vy3XQzdjhIhKGItkhevjXLYJYLr99UDNi77dy9ICwzJ3aV3LrJbfFCIT8p6/NaM=
    rootUser: AgApEdCPSX4PHo8Tq3gs8/SdGUsNmkoROQ+0K9QQdzgJxrw7aCdQfWDcWk2jIR2t/KnlBSnWCxoclVoJqXQSmmaKQWs3ii4FkQiCD+XOri+QHtYJdkoxfDBE4HtDvI7j9rITjUdqNBZ5dpYYueauMiwawMcQ3aytNqrwZPMOXJ8SRLlMZG1lTzVMEYuSyoZwDpcN9XrBMOTqrKg6JTVk+a4w8METpQ9dKAwe7dOFDUpge0AmAfBCWSwrGlNhzmyPOEUu3t7AKT+FS7L9AX3uqVlFdjqhfQ50zM/bYY/o7QsH83f4NpkOrKjTcHOlbExFQnUOYf1qydmuPGVwEVaW5UqoAZtSELCCXDIVLZodbiECIbGX7TI0U5+V+bXe9ZAM/6IR3mIXv2HjQ7TG+fty5BDWiw1B9dr8vOfU1a8PNVDKLT7W4xfwSsk7Yfi8w8EogwUvuveDAbhbmSYexZMv6gw7x2FnL4uUpxuECkm0U5biAHRd/gQlJ8udcVnznS4adCPDMz4bt5kStElPv2JqtkTKvMZJXF/d5uKIFoZnQw+33S0kSHnsc651FX0hH2hXmkyIK2KyMO0asgg3miogV3AzOY/753yt5eP2t4Vj5w4WRuVST6NNVxh9Fd0OsCnhpps+rbeEhXqhLdcb9ROtHBwlfwew8Cu2iTeOfxsn2w1xLW0ITdWCVqJSf3Z3HSxUUm6exK9xbw==
  template:
    metadata:
      name: minio-credentials
      namespace: mi-carpeta-medica-dev
    type: Opaque
