---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: mi-carpeta-medica-dev
spec:
  encryptedData:
    .dockerconfigjson: AgB5mzv5qsQFcUP53+N+dfCStu7FL5OGA1azjK2UjvVwVpQJ4vv7HCP1eZR1jIxVuqSXuCshKRcsIoQqPodtHcPQwfiYo5jq2GU0AY0f0Z0ZyrhLyUkjFtHHTEpD2A/yAjBtr6q2cmXfzZDD5nVt0r3AV2Mv/CuThvl4LAJpSk0dta7t01yvpMhD/87Zb8fWbE+CxCbmdo90cWKFpiZVwiIsJB9T7GdK1NeS5232v+xkWeqK2ATGwLElt+BK3Hzf9R4dFdrnO7qFujIWss8PA/Kg+ltgYbqirp8lWqebhnCBghFgAhjVn3Oh2+TjIrIbaXM61exZTq36t2kng5EPglHIp1SLrgWCn1mb9v6ZYEOQg5xtKfAOH4dkJTGfgg6Wk2oJFk7h51vF0MkbCrry9rtxMbRZdLJ8n6CSN7o4sdLHv1/J+BSEIZNfuKX1k5NCpihaWOfrHtxjMoxvxcInDJ4kSFaElTmMLk4mv4pQW20zDlfbYAkFJQ1os+ONOkfGaLFvkYZgCwDWmZnLvr21qnXuK7oLs7Fm0e4+5qnEPfVrm2nUwFhCYo103GKD376pcVIG7fth6YCqgVWvpLTaaIMtbIappMObQttOI0G600trtPvyqIuI2eqvojcwxP4XSwY1vDGA+UV4Ca4GKPHorTWsU9tQp4hlHTirUKNvza2nsc6O5OmxIoM6WphhrjA8Cc9Y7LMxgIBVVsV6VHOgZENVYwOLaUqwrMZ/IqLZ5RbX/TqBiHbNnlJUkOtPJOVNprLX9YGVb4C5J9RWNrRpqH0y/22oEopbnfxzWIABdoaCgT6OJ4lFmq5hHBXhlLhXXUpTXxYljmLdphPsv+bdvsQhMb0k/aMV2f/u+rP6CW5VD5jqUcYwm17jHvLU8JPEXcjU6GqFrAnBBzjBZhp459n6jZuuBVkaep1VcerD7Ms2ffyFme5Eb7x+xQd/gGGxMCF6yRxVbF7ZXke46Eqz1y4nIvpAd7UBA7D50NQF2323+ME+
  template:
    metadata:
      name: registry-secret
      namespace: mi-carpeta-medica-dev
    type: kubernetes.io/dockerconfigjson
