---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mi-carpeta-medica-api-supabase-secrets
  namespace: mi-carpeta-medica-dev
spec:
  encryptedData:
    JWT_SECRET: AgDIraCvbZ4Dy3WWs+Wf1FV8r6tIyaJ18vG/VaE5PV0KAJqSI/58fdskJstfiBVrKlRBzl4xmjgSWTXtXeegNISk/sc8buAX7T1EQWjlN9oubEOlct5UWqZP045iS4y8sgyt6lirv9L3rKidvqKazPHQAFeP5LN99YlZJn/hUbV0s5fc4bqc+iqMivoGzjcspZWZwsnmzVJv4TmOoAjsz3JINvGI8PnZwi0Ot9vPRUbKOlGbNKMUCsqJbB5WffGRgAU9KWgywS27lVgd6BEzrpEv4BDYHKuyKOf48qQNYRuiDnrhbctqV7iZzUCqA1Dwh//Za0WSIvh/+8PUzGcJzcb81b8P1aVTqbtCPjSI1ioRTrG3A2TsQSWJEAAqbe5qya9/klafCIqoDroeyZGsq3qvUjXIFn3BbxrhJCKK+2NlrJNB4YboZzHDYu3lcmgLUhaGeUs8oR50dUyWj6TwBHRI9VEkMD8jwBzJLlsaw7370I7ES7keGthGGdoi0x0iM0Da1uGetINxP5qW/hqPIugEXURD+1PmUgNwX34q+uoGoaQ7MPk1TF/HQGNRizF0yhSmC4kfbZr+UGbcJZcS5uj6gxHttoel7BSn2qmwQ3LhwSQwiEn/XPBfli0vXgpI8EXbzxdvaIjz5D1+9L/ctnQt2LE6rifuY++xFr9aH4VQq78oZvnoDisveBE1kZoB5jVXi0ebVOP2avUnCw1B7nMf64w9aPetJrO+ZK/XfEE5IOi6QTNyFijFAYu07VwjIU7gjFPlsqRzMLpXFFU7XSI0
  template:
    metadata:
      name: mi-carpeta-medica-api-supabase-secrets
      namespace: mi-carpeta-medica-dev
    type: Opaque
