apiVersion: v1
kind: Secret
metadata:
  name: mariana-toro-basic-auth
  namespace: lulo-demo-landings
type: Opaque
data:
  auth: bWFyaWFuYTokMnkkMDUkaGJNNXZTbzhmaVRtLmlkbVhYTUV6ZTYxdUM0QjQ5SEtVc0gxZGRyVTZXQThzajFOYUtFNlcK
