---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariana-toro-basic-auth
  namespace: lulo-demo-landings
spec:
  encryptedData:
    auth: AgA9rq4ol6YqUJdcnnGHURNYyDxHkG9gRq2IksTcrmjzAuQRya2NSR2C//kW0Ze1tDlwIVdRfE/2ZCWVuMicA6163Ljf5Qf7tO35SUncWRBNzqXVYbSk8qzMSWJUIJSQGjwznAxZhwagAOciT96KpjSHxdboNhw+4jF01rVgQ1KjBsyWJu6EgORivM3fm/5BfLzAPHZpYEl6LkpMBo/Ek6U8TpR4VRPm8EqQljDf1JBVGVOxxcbfGiTYX7PoHKSDIPGdMKv6iVa/lzst6cOYfgWggjo2d3SbsQU2BjdMxt6ND5T4msKZPKxGnlQ2VgkQ5M4AjkMnt9Wr6fD/OpF4BqO22Pw56R+Q1PAfFCbKu4Zmrw2Oowg74DpYyN6oQwq2ggqiE21KrUyxGEy1PjmsevwYwDOrH0T9t97XuLRo6/eAJvEtAzxTuR4S2eZoCq62C9oo62pY0OxzO7a0PKpmSkCPy/PDGfCkgd5qUwTO4zEm2dfwsYEdtirl79XH10nl7I+z1G0PHUoN8W7+6b4eYF19+EvGeJKsjS2LhJt5plLb0Qu786PEwMBTSceIS2S0g0dUhyjKY4Zp+eXxp75MRJS3lUHcFi3BUwQ9oNtSm+PbW3Ug3a16EGxAoVPYkzXXUwxLMjr3V5ubgNy7bcNcSEtVlbQ+Bo3B6dn9MI2Sqi4W7ayfy5+tPEkGBGIqnMuyo/5n/KDGmvMLc//ot+Uh4Z/VV9JtUTN4IseEycMznazxWgZZrz+L2w4gUa698Pn8qtPGyE8csgyHrNaqOeFKKajstonpiCM=
  template:
    metadata:
      name: mariana-toro-basic-auth
      namespace: lulo-demo-landings
    type: Opaque
