apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: ebay-kleinanzeigen-api
  namespace: ebay-kleinanzeigen-api
spec:
  image: docker-registry.registry.svc.cluster.local:5000/ebay-kleinanzeigen-api
  interval: 1m
  secretRef:
    name: registry-secret
