---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: cults3d-mcp
spec:
  encryptedData:
    .dockerconfigjson: AgC2MO2nh2PxkMp/W4gliux/Bo7jIfXFu4f362RMUHehz2NF/aPaYK3A6xfI29kJy5AehHK9HOBVKKwbfhos6BLR6Jkloiz6MRj6NcqCGpAnaI3I40LwRugJc131Fa7TojsX+ZyZFgt0Aarv5DYmYD6qEm55cS8zyAFprYOrHoKfsEjn0iorjKNP5L+aJUxDX9jBTqLebQM6Cq8HJndAZuus7Q+hBh0rkUdsuJqf+Ltf9blt17tujnSMi15BX4KEEDRwydnsfyuRACafz4UrQlPNRtAhkSfVaRgfvTCf7DIea88P9SN4Gn6PQ+DUU5bM7CfWYsv53AqbK1BBJO9/euWK+DmZPIWgfnVg6dMKFrY1lu8UJw3QK2Q75U23vm3X8CHkfXeHXtTRsqXR0Cks/m97kd/BDiwIRcU5D4dGZ7E5V+4qM6Dvv8A8mj++K4cC1PhXq68HNU9VrL/RWadTZxb4+7pmainCiDZ1a5PMcgLOtapf9md6OOvTf8tMBPyV8ujYeO1f7teQOT/KmvGberRbqWgE+qxXCENAF7K0iqMqbuJumIVlpAWN43Bu+xkc7uImI8zR7RaBfgU4TH66yiU4/vq1aN0fxRwc5hIl+/VhEwH3NPEKvqxixpR+/34HJDUtuU/HRxiU1VXAN+MjAcAnOYiKPkEAe5M6X6U83nt2E8zs7C61TeCHqRuRaO0ZI3mYNaoY/60G4CjMkASJESwC2wDoEJ7yrERrRYvlT43c/zu4g06FZfcBbkOeAoKBktfEbAtBhsbH4RuvnauUAVylQDkUWmeay8JX1vUrcP760Jbvk0U6QFPN202e/pQnaQ6qNbCdpOJoQq7krvECizJDXtXZL6SOrzd2sUusuRwU9xfKV2kSMFm66ypSN2Fdwhef+3ZNVc11MaqyP7CY/qeccQ+LcpYcK/+zum/eNcnpTWnt84QJgf+uZMzC6L0FSoKKhzOVubnImDSaA81e0d9wVF4LscfetYGi8TdI526t29ln
  template:
    metadata:
      name: registry-secret
      namespace: cults3d-mcp
    type: kubernetes.io/dockerconfigjson
