---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cults3d-mcp-secrets
  namespace: cults3d-mcp
spec:
  encryptedData:
    CULTS3D_API_KEY: AgBxoQcFC0bJjBedmecm3ImYZyxV1IkPXXd1sOpbCeRI3Wqm8BAPIt47BVlrieSSCMASO2fdNoYRlsaSQ4xHz66wjC1YI6pCtOlQWzdUzlPmOVhbvyvmK2i2OmMx09/t9PZhwpJLA6bncXnV1EZYRLpx5KFsKZozEUiVpxV9+OHlzuupJo7cu/E3YHlZyJl9AvchsDrzxhydK+w0nhb0dq1VJidjbzTMLIM8zXk46WlbbOe0AOH/3z8d+c/tcBvCwORx3oQcWjnjXH8CHXxIP7pm85nwN3TSp/p9f3JAaviB9ehRxa+rcrWRESYuNgVOjy1hbmgechT9nlFUqwN54ZBrva5kctYTHTeWWKOe0n7aD1noox4EeODnBJEypro6WYLr7CqOTK/DWKZf+YPoXISeVZbypCZsXVbQVx7uEnwnFKcGo9zqZOFLLoyQbyx2Ue7nx5GNAcLog+D9HMY+YwgQ6X3sBj5Fy7MlvV/Fit6lqn4pcp4ZzqOA4RkwwJwx0QmcHGlj3w40I4ccACXWsDgTjb8zZPDxBkCzE1ab5fAVqjogsAg/Z8yTQiYCxE8rmXRCvln21SgdLb0WEP6XFGAn2wRPv9z03xi464Z7+2oA1+uTkfQcHLlqZPTkTxc+wnrZlYRXNkhqwetYaU98R1SvPfvSexG2w1GjlhUiedGHYtvIudg1C5l6koB7yfBk4Mp1WaPCwyT9I8KjXKKmOvAwDH2yIZCRw1/L
    CULTS3D_USERNAME: AgBr6ejAPfH39u23ohX9Mn0qHN8/EJHaS339JjgSS9hbdiHIaaMIg6LnDOzs9vyPYNiuHPoe5eegPneXwN+FlVbd7pzWN8CKR18Azj9dXeEvA7y0sCB8JwUeNa3Tt3dl0lM0oM8V04fOcudetaEzsfztfaTQWEUa3ZqkhFkt8ojGOD88hXmUGHqBywu6oLQtnCTOqauLruJWtupy8z21iBMNIJcuICwbngoN+gorL0jTVcJ7gmHicyHSkKJiNBQ9VvkZyuzrbO/HhPz8bLnthongI4Y62CTCUoSufSVS/R4rsz6PrcZ+KHxWmk1bJ93WwiOaQXY7xl8gz1uEQm0HPem3N1JaGzQyUUEEvkC/0W2qyZGg2wfRPj4zZYvGGvgERVZW/l+sgNpBe7X0OwQ54ibisDCM2LPmfbYShT8Fwvk7bR+AzGT7a0KnsCGKh3id+r1GhCXvblDW46+6h3fRBVt0E2GSjU6SFyTYIrFXgJzy+TcE672LUwY3J01m+KpyXczkVeIqMfz6gvKFrfTNAP5wEFVdFd6Y2U5LAZ+TtIfzcviA1OQyYeQyo36Nj8zWTlN94m71GMGlu8BsFq04Z6IuAYXlFIeWJqeZk46XbOmqpUNW8SxljyIV47u8+AZ+pto6nz3ZfgndmNthw9KzaQBKFkmWcFjVN2TLG0TGjFV8KhXBCnKLtvK7ygbq8XuW7FlRfrYAkkK7
  template:
    metadata:
      name: cults3d-mcp-secrets
      namespace: cults3d-mcp
