apiVersion: v1
kind: Service
metadata:
  name: cults3d-mcp
  namespace: cults3d-mcp
  annotations:
    metallb.io/loadBalancerIPs: "192.168.2.102"
spec:
  selector:
    app: cults3d-mcp
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8000
