apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: ghcr.io/fluxcd
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  cluster:
    type: kubernetes
    size: small
    multitenant: false
    networkPolicy: true
  sync:
    kind: GitRepository
    url: https://github.com/yesid-lopez/homelab.git
    ref: refs/heads/main
    path: clusters/production
    pullSecret: flux-system
  wait: true
