apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - redis.yaml
  - postgres-cluster.yaml
  - sealed-secrets
  - image-automation
