---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cults3d-mcp-secrets
  namespace: print3d-mcp
spec:
  encryptedData:
    CULTS3D_API_KEY: AgAFKjoyDV/qGjk2Q8PSBAZrr2zE+jS5+jYaZLuM1UodM9ExINWn0YnFgRZhhFYOlYdj6Y53vRfI2Zmtp354Y3Pcsj/uK5XoDEj/dhoWMK9922L2fBGNB++/j21c2ZZQ5mSrUV47C7sLWNxDqd3en2S5HbEjmKwbzj+wuqMQuaXkjhJOK94dHtUosyPu+dewKk+n4lQxeG/cNQC2mvxSj+gEo7LKGii5bA8Qhpfb5+FaUxZ2+tP8QyIzj0pIvumjJMi68jocgkChxM/5LJRV/4bV+WD4iHYs4aTqd0tPvXV9jtx50RGqEuygGioHJPk/GU9tl7nI2Hg4vM/oOHgGc1wk0Iez+l0+KehRmo1HvtASLVfz6FDhy6ibpvBJeZGUd74HgPZYRkoKkFf9K9F1S3E9iLeQu9GiNkNTLzEeJ14DW6J1ncIrRTOok+AEc87U4QwvbsdMID7EGp/rOxuP+frRBsG6bsgFNuSLSO63LFmDveELDHOLFsDQaV6ZhfijOMGtIntgw3BmjMmnFz2vegMTEa1ZW1Tfcd7lcy3Q677dUPCHNHyW64LfVEneviSSO52EZf6G079Vur/fkhDWswmr8GIpT3jikDZpjT8mY6SAPZOreyeasP7eJvBCUXKuoeTogh/WJjapjI9d8cM/3fN3AMD7fOFwQAd0BIDbwanRnYFYdsMctOTp5e5k+lmNNwWypCSzyBLL6sju5lzh0zXhkmyD1FEdhhQh
    CULTS3D_USERNAME: AgCuAgbG03FHdqQVUTuQU2I46gAwuP429V6n3dcYe2ufMkB4kdXl5RzhbGswZ7sL1d+VVdJroixPQne7IafjmeqsvGC0am4Mt/CM3jL3v1QfAE6DEXDa4VuCQSknqMTrcGj6aa2P6dRNt5z7SSBzSFiGdbeUZDgsts6x7OPg+hF7fA5lpt84d5zdLuPg367xKsnwivc/4FnmqabC+jIbzrFg7iOdcY9WBcUyjnYPO7MwisUkfPmJJFUo8028a+ixmfu8d6SmjOS2GJFxPaX/voMibMp1UoWDDHpiG7ycTykYCDJXSndOiDANTfIHeQ56iJNhUeeyAvvcgwH1sZlxkK+4+pO40zzt8EviMRaTQ1PaLjgg0k2E1HJo2XQcNiumF3FCb1Htk6C8y+3Nnn4mXPjaShhiWjzEGYtTWOOMF2bg8FTTBwWA4ZlkezH5jYfsLxo/O9g7dRcN9ajQYsyiY9RI/kR5K6tLdeg42qUbtTkJeIy+6PPhPLA6afEnNNYFHmarFF0Vqg7IPRxVdtUh5sblxpA0AuF3GjQneN/x7XGn/SL4EaNvJZURxR65VqnQjDEDFa1voGbBcrbEY8Uw4ArCn73Buv1aURBv4NKjkFfW6XnfefwE/2cv40xjFE6QBIbB5Z03344VkKLaFnajxnW7s9SGZlj7noH3gzh/QusXzqfF9WHaZYU5hDlS3nm2g0DhWm3+aSFE
  template:
    metadata:
      name: cults3d-mcp-secrets
      namespace: print3d-mcp
