---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secret
  namespace: print3d-mcp
spec:
  encryptedData:
    .dockerconfigjson: AgBdjL5aODYKUCFVti/kMGb1+4swx6Qeq9Q+rYwN+Y3uawA4cKe73Y/aYW3j7H/2tXr5ARd5NoHAkMSqJ3pLI2hoKkgJvIk8bS+RVkwj0pudGGniTmDTStc5OgLxoYRqPMme28QU/Xt26GuEzdNjaebNfuFPJ8mVd/S6EaplIFnW5O/DFc1lrGeTrawaLX+WQztRPx75Fs2FTGmDG0X6qawgsUMopQGkTcNjqSePkJgskz2/EU65IRmiQYSx1Cl8L8PiMU9W5EG6HWFK5F89v2J2QqzdHwyBLdA0Qvnk0nR4rapNFYxCXuO1ToQyegDoXt55mMo9Vx8BCegj1A4coL84xjDihQnBsyrrze3Gb8NcB1VzC154oOLPopvCTG0h0LCSJAxoy6qqSQHS/7b9rh5FptIyRtKrBcaUH0zO6NdbtUCy8YeJgTriBCTODoCSTC/eFRjoFugz+KNI9eOtNtqBVy4aC/2RrpxSroUMA1wy8eGrqyxhDe35jntXR5GgVi4hLf+6y0RH7P6sBe6N2SBdFeb4s9YJDkizkidAvPZF8+9/MEq6aEk3jEYacRCfVC3OudlBpZPKuA13suCQhe6kMTV3ONvswb6N/8NjGC6MocQy+Z2TPtJaI2aTXHON8B45CHS4x2SJJk+9tvu578jVwpyjTwxGATioX9fWF2GP5A302QTCmoFWW7kD0Bz/B70pbRcwSjOvp4nIAtylSZW0YKRyHZPTSAEplnDSfVinadIysWMxT9XdtImyzDtU97a9Sw2Etr+PBVvFDiari7OCDG6M1kzIvaCxP0LOTdV1zVHdiuVz2RRk1eOGL2ok6dZpVBEUEoLvEHw1rxyQF1seUY+7n4VfqQ/2ZXk5kQE4uYkWJYtmyiwIoX1BuGNzRnjHWYtYzBOTkQfM5IYZHlPZJ7HDsi0YPvwfg2ATNGyQxobJktvVnNUi0WIb1xIUQmqxb2DEL8KBrMKg0Anf5HDiUQHpaQwifitGR9rDsaq8G32y
  template:
    metadata:
      name: registry-secret
      namespace: print3d-mcp
    type: kubernetes.io/dockerconfigjson
