---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thingiverse-mcp-secrets
  namespace: print3d-mcp
spec:
  encryptedData:
    THINGIVERSE_APP_TOKEN: AgAFhiXyWs9WIDzo9mo2yA3+KT/PjvlUtaws30wDWi6joU96HXnGz9rJrXB8IoepgJxrFvUMn18YQbAzk6IOibD7NS7ZcLiFt+V4052q0e4hVGzVBsWmmOCOvVUE1Zr5oXWNRfjivJJvgdaM5P20N7iDrd/DC+AMNnrFtpLq43Lpzff8xmVUfX1wrMQ5kMNCBkXhH/iipH4PgNV1gxeqLemBihCEUzy5hd5lKZRvu8gyO/X76z/5Fex78XYSUSkgE59T7AQ+Hobo3f3x0Xer8bWoW88XG9cAS+k2YZKayDzn4S7pwN2orOJRjS1RjSEpWX2dHbK5EzjvXz4zsXSVmnixiXQ17dnHMfljkHpzpiEb/vC1OwQH6567/mT4zWHYVQ5dM5JYJ+un9BP0y5gMxeYMPGv8wnUB/rnIabNWqQ6z1wDghoAJwlMzcP4N2KHg/lFPuV8T6I0+k5LqrERvYBiX+KMVtzPSuhDxpmdExwDZiyGhx3bqZwAj8gYKXjECbf75At9ekkSYFVCCt3omJTErShyQIq+Zjv5AwjueRmabvhpPitvfdzrlZwEKR5+gF7wzZAO1DQlPeEXNqsUcneuv0+dTC5ZUt2DRGuEvfZfcGxi8DWmkVsE1PldzYZFTwcbwRM4z8lAVd6IwTcdgRr1o4aT8TSCtSFOfBp+IHbjHBWBkdpQrlgCawHB7/hXMTp2KDeQlnJJh5hrgONBRDmXy0kEqhpDfXnBp31j8SNalqA==
  template:
    metadata:
      name: thingiverse-mcp-secrets
      namespace: print3d-mcp
