---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: daniela-rivas-basic-auth
  namespace: lulo-demo-landings
spec:
  encryptedData:
    auth: AgAwQ2wkyMCnIOyxqkEcLV4bytq/F7RrPd9SQU4hI314xwmMcgOk2oy+Yorg3JZ9SMR0DXXWfcmeEPCAKWUtuZkEBdjcyXsgykTUrc5ZKZaocrwi6HePJ4Xmy2Ad3iQE726NJVza9RIzt68yHOoyg0wFNbsHR1pNEFILyjjJb1rJJg+4Waie772a7ipeRAdg/DwXBjggHFdQCGZ8cjPKwk8qYWdx8a+lOaTtfspuEwtzMFZgp4KcQEsT/3bvQOYvRZe0U6mUvo+qdAxcfaX9L0KSl7AvgAh/kqZg2pc5378h8ft/aP0xWHv6uIqirJO7UZcNwihweo9xqRPZh9bhcB8sx8OwWq2Zi9P8vVf5dce+6FeN96HRKNCgevtSaS6tZR1vEXdYLcuHzXeXfSKH342uBpMXdsu3FUmBgfu/bBAh4X1LEDz61AnVPHKxyRhCx7AlVPqWB0QylWhpBiWNMvIy7N82q4mJgqzyKtMR/gN/FQ4tTARjAEUaMZK6ZXqwhpvlYWH/0fOghMfrkv16/RvmGwqso3EWL66s9v8SseEvIMROg0MqQsjEB0s9xa8tOyUR7cI8Mn72w5UxLhej7VzWMnrHialkuFhW8T45yymaGb8YiUMLHq6wVIUN9dtA7EPlfZMc1xrVg6WAgeX8islhXHh98LuiHUuvUrdArJ9qfOYWX1VIfch3gsSsva75BC5ViPwCFQX3DYPTUCy+J2nr3++iqhNRlR07U9FQ2WoGZgz+WQcSN43z2ZvoVkxpM76TS5bZj/tB8jplQcAMaRqUg1brYHY=
  template:
    metadata:
      name: daniela-rivas-basic-auth
      namespace: lulo-demo-landings
    type: Opaque
