apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - sealed-secrets
  - image-automation

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: resumelo
