apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: medidocs-api
  namespace: medidocs-api
spec:
  image: registry.yesidlopez.de/medidocs-api
  interval: 1m
  secretRef:
    name: registry-secret
