apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: laura-galeano-psicologa
  namespace: lulo-demo-landings
spec:
  image: registry.yesidlopez.de/laura-galeano-psicologa
  interval: 1m
  secretRef:
    name: registry-secret
